# Determining appropriate metric thresholds

The purpose of this notebook is to derive the minimum threshold parameter for the metrics. The logic was adapted per DeepEval documentation for the answer_correctness metric.

Steps:
1. Re-ran data_generation/main.py to generate answers alongisde retrieved chunks.
2. Manually labelled the dataset for the answer_relevancy, context_relevancy, and faithfulness metrics. The labelling for cultural_neutrality and tone_attunement were retrieved through surveys sent out to RC members where they were asked to annotate the QA pairs.
3. Used that labeling to derive an expected pass rate — e.g. if 75% of manually reviewed cases are acceptable, target is a 75th percentile threshold.
4. Ran main.py to generate the evaluation framework metric scores.
5. Compared results.
6. Discussion and next steps.

# Extracting metric scores from DeepEval

The scores will be calculated in two parts: the humanitarian metrics on Dataset A (`qa_pairs.csv`), because they were annotated by RC members; answer_relevancy, context_relevancy, and faithfulness on Dataset B (`qa_pairs_annotated.csv`), because they contain the context for the answers, and they were manually annotated by me.

Here the scores are

In [163]:
import os
import ast
import pandas as pd
from rich import print
from deepeval import evaluate
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval.models import AzureOpenAIModel
from deepeval.metrics import AnswerRelevancyMetric, ContextualRelevancyMetric, FaithfulnessMetric, GEval

In [241]:
# Loading Dataset B
data = pd.read_csv('../data/qa_pairs_annotated.csv')

In [60]:
pd.set_option('display.max_colwidth', None) # Show full content of each cell

In [4]:
# CUSTOM MODEL
endpoint = "https://510-ai-research.openai.azure.com/"
model = "gpt-4.1"
deployment = "gpt-4.1-students"
# loading variables from .env file
subscription_key = os.getenv("azure_subscription_key")
api_version = "2024-12-01-preview"
# model
custom_model = AzureOpenAIModel(
  model=deployment,
  api_key=subscription_key,
  azure_endpoint=endpoint,
  api_version=api_version,
  deployment_name=deployment
)

In [5]:
# TEST CASE CREATION
test_cases = []
for i in range(len(data)):
    tc = LLMTestCase(
        input=data['user_input'][i],
        actual_output=data['bot_output'][i],
        retrieval_context=ast.literal_eval(data['context'][i]),
    )
    test_cases.append(tc)

## Metric Calculation

Default threshold from DeepEval is 0.5.

In [6]:
ar = AnswerRelevancyMetric(
    threshold=0.5,
    include_reason=True,
    model=custom_model
)
cr = ContextualRelevancyMetric(
    threshold=0.5,
    include_reason=True,
    model=custom_model
)
f = FaithfulnessMetric(
    threshold=0.5,
    include_reason=True,
    model=custom_model
)

evaluation_results = evaluate(test_cases=test_cases, metrics=[ar, cr, f])

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1-students (Azure), strict=False,
async_mode=True)...

✨ You're running DeepEval's latest Contextual Relevancy Metric! (using gpt-4.1-students (Azure), strict=False,
async_mode=True)...

✨ You're running DeepEval's latest Faithfulness Metric! (using gpt-4.1-students (Azure), strict=False,
async_mode=True)...

c:\Users\dari\conda\envs\hia\Lib\site-packages\rich\live.py:256: UserWarning: install "ipywidgets" for Jupyter
support
  warnings.warn('install "ipywidgets" for Jupyter support')

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 0.75, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.75 because while the response partially addressed the user's request for a doctor, it included irrelevant information about the chatbot's name, which did not contribute to solving the user's need., error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons provided for irrelevancy., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—the actual output aligns perfectly with the retrieval context. Great job!, error: None)

For test case:

  - input: I need a doctor.
  - actual output: Hello! I'm Aidly, the HIA chatbot. I can help you find information about doctors in the HIA app. Could you please specify what kind of doctor you need or any particular specialty you're looking for?
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because the response was fully relevant and addressed all aspects of the input. Great job staying focused and helpful!, error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy were provided, indicating a complete lack of contextual connection., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying true to the retrieval context!, error: None)

For test case:

  - input: I am pregnant and my landlord kicked me out because he doesn’t want a baby in the house. I need to see a doctor for my pregnancy and I also have nowhere to sleep tonight. I don’t know what to do. I am so tired of this.
  - actual output: I'm really sorry to hear about your situation. You have the right to be safe and to receive medical care during your pregnancy. It sounds like you may need urgent support for both housing and healthcare.

I can help you find information about your rights as a tenant and pregnant person, as well as resources for emergency housing and medical care. Would you like me to look for this information for you?
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because every part of the response directly addresses the input, offering relevant support and guidance without any irrelevant information. Great job staying focused!, error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy provided., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying true to the retrieval context!, error: None)

For test case:

  - input: I don't have a place to stay because I escaped from my trafficker. I don't know where to start.
  - actual output: I'm really sorry to hear about your situation. It’s important to find safe shelter and support as soon as possible. In the HIA app, you can look for resources related to emergency housing, shelters, or organizations that help people escaping trafficking. Would you like me to help you find information on safe places to stay or support services available through the app?
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 0.8, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.80 because, while the response mostly addressed the user's request for food, it included an irrelevant introduction of the chatbot's name, which did not contribute to solving the user's need. This extra information prevented a higher score., error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy were provided., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying true to the retrieval context!, error: None)

For test case:

  - input: I need food!
  - actual output: Hi! I'm Aidly, the HIA chatbot. How can I assist you with food-related information in the HIA app? Are you looking for places to get food, food services, or something else?
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: Great job! The score is 1.00 because every part of the response was relevant and directly addressed the user's concerns., error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy were provided., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying completely faithful to the retrieval context!, error: None)

For test case:

  - input: You referred me to an organisation for asylum and they told me I don’t qualify. Nobody is helping me. I have been going from place to place and everyone keeps saying the same thing. What was the point of sending me there?
  - actual output: I'm sorry to hear about your difficult situation. I want to help you as best as I can. Could you please tell me which organization I referred you to for asylum? This way, I can check the information and see if there are other options or resources available to assist you.
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: Great job! The score is 1.00 because all statements in the output were relevant and directly addressed the user's concerns., error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy were provided., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying perfectly faithful to the retrieval context!, error: None)

For test case:

  - input: I have applied for a Dublin claim, and I have been waiting for a response for weeks now. This is incredibly frustrating. I have family here that depends on me and I feel completely stuck.
  - actual output: I'm sorry to hear about your frustration with the Dublin claim process. While I don't have access to specific case statuses, I can help you find information on how to check the status of your Dublin claim or provide guidance on what steps you might take next. Would you like me to look up information on checking the status of a Dublin claim or on support services available to you?
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: Great job! The score is 1.00 because the response was fully relevant and addressed the user's concerns without including any irrelevant information., error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy provided, indicating a complete lack of contextual connection., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying true to the retrieval context!, error: None)

For test case:

  - input: I need help because I am in danger, but I do not want to go to the police because I am afraid of being deported.
  - actual output: I'm really sorry to hear that you're in danger. While I can't provide emergency assistance, I strongly encourage you to seek help from trusted local organizations or support services that can assist you safely without involving the police if that is your concern. If you want, I can help you find resources or information within the HIA app that might be able to support you. Would you like me to do that?
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: Great job! The score is 1.00 because every part of the response was relevant and directly addressed the user's urgent situation., error: None)
  - ❌ Contextual Relevancy (score: 0.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.00 because there are no relevant statements in the retrieval context and no reasons for irrelevancy were provided., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions listed, indicating the actual output aligns perfectly with the retrieval context. Great job staying faithful to the source!, error: None)

For test case:

  - input: I am running away from my abuser, who is searching for me and my children. I do not know where I am and I am very afraid. What can I do?
  - actual output: I'm really sorry to hear that you're in this situation. Your safety and the safety of your children are the most important things right now. Here are some steps you can consider:

1. Contact Emergency Services: If you are in immediate danger, please call emergency services (such as 911) right away.

2. Reach Out to a Domestic Violence Hotline: They can provide you with confidential support, advice, and resources tailored to your situation.

3. Find a Safe Place: If possible, go to a shelter or a trusted friend's or family member's home where your abuser cannot find you.

4. Keep Important Documents and Essentials: If you can, keep identification, important documents, some money, and essentials for you and your children with you.

5. Consider Legal Protection: You might want to look into obtaining a restraining order or protection order against your abuser.

6. Use Technology Safely: Be cautious with your phone and online activity, as your abuser might track you through these means.

If you want, I can help you find specific resources or information within the HIA app that might assist you. Please let me know how I can support you.
  - expected output: None
  - context: None
  - retrieval context: []

======================================================================

Metrics Summary

  - ✅ Answer Relevancy (score: 0.8571428571428571, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.86 because the output mostly addresses the user's need for shelter, but mentioning the chatbot's name is unnecessary and does not help with the user's situation, preventing a higher score., error: None)
  - ✅ Contextual Relevancy (score: 0.8699186991869918, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 0.87 because, while many statements are highly relevant to someone seeking shelter (e.g., 'You should go to one of the registration points to get shelter.' and 'The crisis shelter of 'Stay away from my body' can help you.'), there are also several statements in the retrieval context that are not relevant to the input, such as those about pets, education, and resources for people offering shelter, which lowers the overall contextual relevancy., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying completely faithful to the retrieval context!, error: None)

For test case:

  - input: I'm homeless and looking for a shelter. I am very tired. I don't have anyone to help me.
  - actual output: Hello, I am Aidly, the HIA chatbot. I'm sorry to hear about your situation. If you are fleeing domestic or relational violence, you can call the crisis shelter "Stay away from my Body" (Blijf van mijn Lijf-huis) for help at the free number 0800 0117.

If you are looking for general shelter, you should visit a municipality ("gemeente") in the Netherlands. Municipalities register displaced persons and help find housing and shelter. You can also visit a Humanitarian Service Point run by the Red Cross, where you can rest, eat, drink, charge your phone, and get information about shelter options.

If you want more detailed information or assistance, please let me know.
  - expected output: None
  - context: None

⚠ WARNING: No hyperparameters logged.
» ]8;id=354486;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 20.66s | token cost: None)
» Test Results (21 total tests):
   » Pass Rate: 19.05% | Passed: 4 | Failed: 17

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

In [7]:
results = []
for test_result in evaluation_results.test_results:
    row = {
        "input": test_result.input,
        "bot_output": test_result.actual_output,
        "retrieval_context": test_result.retrieval_context
    }
    for metric_data in test_result.metrics_data:
        row[metric_data.name] = metric_data.score
        row[metric_data.name + "_reason"] = metric_data.reason
    results.append(row)
results_df = pd.DataFrame(results)

In [8]:
results_df.head()

,input,bot_output,retrieval_context,Answer Relevancy,Answer Relevancy_reason,Contextual Relevancy,Contextual Relevancy_reason,Faithfulness,Faithfulness_reason
0,I need a doctor.,"Hello! I'm Aidly, the HIA chatbot. I can help ...",[],0.75,The score is 0.75 because while the response p...,0.0,The score is 0.00 because there are no relevan...,1.0,The score is 1.00 because there are no contrad...
1,I am pregnant and my landlord kicked me out be...,I'm really sorry to hear about your situation....,[],1.00,The score is 1.00 because the response was ful...,0.0,The score is 0.00 because there are no relevan...,1.0,The score is 1.00 because there are no contrad...
2,I don't have a place to stay because I escaped...,I'm really sorry to hear about your situation....,[],1.00,The score is 1.00 because every part of the re...,0.0,The score is 0.00 because there are no relevan...,1.0,The score is 1.00 because there are no contrad...
3,I need food!,"Hi! I'm Aidly, the HIA chatbot. How can I assi...",[],0.80,"The score is 0.80 because, while the response ...",0.0,The score is 0.00 because there are no relevan...,1.0,The score is 1.00 because there are no contrad...
4,You referred me to an organisation for asylum ...,I'm sorry to hear about your difficult situati...,[],1.00,Great job! The score is 1.00 because every par...,0.0,The score is 0.00 because there are no relevan...,1.0,The score is 1.00 because there are no contrad...

In [9]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   input                        21 non-null     object
 1   bot_output                   21 non-null     object
 2   retrieval_context            21 non-null     object
 3   Answer Relevancy             21 non-null     float64
 4   Answer Relevancy_reason      21 non-null     object
 5   Contextual Relevancy         21 non-null     float64
 6   Contextual Relevancy_reason  21 non-null     object
 7   Faithfulness                 21 non-null     float64
 8   Faithfulness_reason          21 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.6+ KB

## Merging the two together

In [10]:
data = data.rename(columns={"user_input": "input"})
merged = results_df.merge(data, on="input", how="inner")

In [11]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   input                        21 non-null     object
 1   bot_output_x                 21 non-null     object
 2   retrieval_context            21 non-null     object
 3   Answer Relevancy             21 non-null     float64
 4   Answer Relevancy_reason      21 non-null     object
 5   Contextual Relevancy         21 non-null     float64
 6   Contextual Relevancy_reason  21 non-null     object
 7   Faithfulness                 21 non-null     float64
 8   Faithfulness_reason          21 non-null     object
 9   bot_output_y                 21 non-null     object
 10  context                      21 non-null     object
 11  answer_relevancy_label       21 non-null     int64
 12  context_relevancy_label      13 non-null     float64
 13  faithfulness_label           13 non-null     float64
dtypes: float64(5), int64(1), object(8)
memory usage: 2.4+ KB

In [12]:
merged.drop(columns=["bot_output_y", "context"], inplace=True)
merged.rename(columns={"bot_output_x": "bot_output"}, inplace=True)

In [13]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   input                        21 non-null     object
 1   bot_output                   21 non-null     object
 2   retrieval_context            21 non-null     object
 3   Answer Relevancy             21 non-null     float64
 4   Answer Relevancy_reason      21 non-null     object
 5   Contextual Relevancy         21 non-null     float64
 6   Contextual Relevancy_reason  21 non-null     object
 7   Faithfulness                 21 non-null     float64
 8   Faithfulness_reason          21 non-null     object
 9   answer_relevancy_label       21 non-null     int64
 10  context_relevancy_label      13 non-null     float64
 11  faithfulness_label           13 non-null     float64
dtypes: float64(5), int64(1), object(6)
memory usage: 2.1+ KB

## Answer Relevancy

In [14]:
# Extract the labelling column
label = merged["answer_relevancy_label"]

# Calculate the percentage of entries with answer_relevancy_label = 1
count = 0
for val in label:
    if val == 1:
        count += 1
print(f"Number of entries with answer_relevancy_label = 1: {count}")
total_entries = len(label)
print(f"Total number of entries: {total_entries}")
relevancy_percentile = (count / total_entries) * 100

print(f"Percentage of entries with answer_relevancy_label = 1 from manual annotation: {relevancy_percentile:.2f}%")

Number of entries with answer_relevancy_label = 1: 20

Total number of entries: 21

Percentage of entries with answer_relevancy_label = 1 from manual annotation: 95.24%

In [15]:
cols_to_display = ["input", "bot_output", "Answer Relevancy", "Answer Relevancy_reason", "answer_relevancy_label"]
ar = merged[cols_to_display]

In [16]:
threshold = 0.5  # DeepEval default

# Pass rate (from labels)
my_pass_rate = (ar["answer_relevancy_label"] == 1).mean()

# DeepEval's pass rate (at default threshold)
deepeval_pass_rate = (ar["Answer Relevancy"] >= threshold).mean()

print(f"My pass rate: {my_pass_rate:.2%}")
print(f"DeepEval pass rate at threshold {threshold}: {deepeval_pass_rate:.2%}")

My pass rate: 95.24%

DeepEval pass rate at threshold 0.5: 95.24%

### Do we agree on which instances pass and which fail?

Passing labels

In [ ]:
print(f"Passing rows (my labels): {ar[ar['answer_relevancy_label'] == 1].index.tolist()}")
print(f"Passing rows (Deep Eval): {ar[ar['Answer Relevancy'] >= threshold].index.tolist()}")
print(f"Rows which don't match: {set(ar[ar['answer_relevancy_label'] == 1].index) ^ set(ar[ar['Answer Relevancy'] >= threshold].index)}")

Passing rows (my labels): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20]

Passing rows (Deep Eval): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20]

Rows which don't don't match: set()

Non-passing labels

In [28]:
print(f"Non-passing rows (my labels): {ar[ar['answer_relevancy_label'] == 0].index.tolist()}")
print(f"Non-passing rows (Deep Eval): {ar[ar['Answer Relevancy'] < threshold].index.tolist()}")
print(f"Rows which don't don't match: {set(ar[ar['answer_relevancy_label'] == 0].index) ^ set(ar[ar['Answer Relevancy'] < threshold].index)}")

Non-passing rows (my labels): [13]

Non-passing rows (Deep Eval): [13]

Rows which don't don't match: set()

Non-passing labels

The passes and failures overalap perfectly, therefore we can compute the target threshold directly.

### Applying the percentile method with target

In [239]:
scores = ar["Answer Relevancy"].tolist()
sorted_scores = sorted(scores)
print(sorted_scores)

[
    0.0,
    0.7333333333333333,
    0.75,
    0.8,
    0.8,
    0.8181818181818182,
    0.8333333333333334,
    0.8571428571428571,
    0.9166666666666666,
    0.9166666666666666,
    0.9230769230769231,
    0.9375,
    0.9411764705882353,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0
]

Sorted ascending, `scores[1]` is the second-lowest score = 0.73.

DeepEval's formula:

In [150]:
index = int(len(sorted_scores) * (1 - relevancy_percentile / 100))

In [151]:
index

1

In [240]:
print(f"Answer Relevance threshold for {relevancy_percentile:.2f}% percentile: {sorted_scores[index]:.2f}")

Answer Relevance threshold for 95.24% percentile: 0.86

## Contextual Relevancy

In [111]:
# Extract the labelling column
label = merged["context_relevancy_label"]

# Calculate the percentage of entries with context_relevancy_label = 1
count = 0
for val in label:
    if val == 1:
        count += 1
print(f"Number of entries with context_relevancy_label = 1: {count}")

def has_context(ctx):
  if isinstance(ctx, str):
    ctx = ctx.strip()
    if ctx in ("", "[]"):
      return False
    try:
      ctx = ast.literal_eval(ctx)
    except Exception:
      return True
  return bool(ctx)

total_entries = merged["retrieval_context"].apply(has_context).sum()
print(f"Total number of entries (answers with context chunks): {total_entries}")
context_relevancy_percentile = (count / total_entries) * 100

print(f"Percentage of entries with context_relevancy_label = 1 from manual annotation: {context_relevancy_percentile:.2f}%")

Number of entries with context_relevancy_label = 1: 2

Total number of entries (answers with context chunks): 13

Percentage of entries with context_relevancy_label = 1 from manual annotation: 15.38%

In [112]:
cols_to_display = ["input", "bot_output", "retrieval_context", "Contextual Relevancy", "Contextual Relevancy_reason", "context_relevancy_label"]
cr = merged[cols_to_display]

In [113]:
threshold = 0.5  # DeepEval default
cr_labelled = cr[cr["context_relevancy_label"].notna()] # to not catch NaN-labelled rows as mismatches

# Pass rate (from labels)
my_pass_rate = (cr_labelled["context_relevancy_label"] == 1).mean()

# DeepEval's pass rate (at default threshold)
deepeval_pass_rate = (cr_labelled["Contextual Relevancy"] >= threshold).mean()

print(f"My pass rate: {my_pass_rate:.2%}")
print(f"DeepEval pass rate at threshold {threshold}: {deepeval_pass_rate:.2%}")

My pass rate: 15.38%

DeepEval pass rate at threshold 0.5: 30.77%

### Do we agree on which instances pass and which fail?

Passing labels

In [93]:
labelled = cr[cr['context_relevancy_label'].notna()] # to not catch NaN-labelled rows as mismatches
print(f"Passing rows (my labels): {labelled[labelled['context_relevancy_label'] == 1].index.tolist()}")
print(f"Passing rows (Deep Eval): {labelled[labelled['Contextual Relevancy'] >= threshold].index.tolist()}")
print(f"Rows which don't don't match: {labelled[(labelled['context_relevancy_label'] == 1) !=(labelled['Contextual Relevancy'] >= threshold)].index.tolist()}")

Passing rows (my labels): [8, 12]

Passing rows (Deep Eval): [8, 11, 12, 16]

Rows which don't don't match: [11, 16]

In [99]:
non_matches = labelled[(labelled['context_relevancy_label'] == 1) != (labelled['Contextual Relevancy'] >= threshold)].index
print(f"Non-matching rows (Rows I matched as non-contextually relevant): {cr.loc[non_matches, ['input', 'retrieval_context', 'Contextual Relevancy', 'Contextual Relevancy_reason' ]]}")

Non-matching rows (Rows I matched as non-contextually relevant):
input  \
11  I am from Ukraine and I work in a factory. I live with my other colleagues, and my boss pays for my rent,
utilities, and gives me an allowance. I want to go home this Christmas to visit my family, but he refuses because
he says it's the busiest season and if I leave everyone will want to go home as well, so we will all lose our jobs.
Can you help somehow?
16
I have been to 3 hospitals, but they refuse me because I am undocumented. I am in immense pain and need immediate
attention. I am in Amsterdam. What do I do?





























































































































      retrieval_context  \
11  [Document: What are my working rights when I work in the Netherlands?\n\nDisplaced Ukrainians have the same
labour rights as Dutch employees.\n\nThese rights include a safe working space, regular breaks, and the
minimumwage.   \n\nFor questions about labour rights you can share the flyer 'Know your rights when you work' with
the person affected.\n\nFor Ukrainian people this is available in:
-\n\n[English](https://www.comensha.nl/media/jizlbk4d/2026-know-your-rights-flyer-oek-ontheemden-eng.pdf)
-\n\n[Ukrainian](https://www.comensha.nl/media/kdcfdy13/2026-know-your-rights-flyer-oek-ontheemden-oek.pdf) -
[Russian](https://www.comensha.nl/media/fbtnesz5/2026-know-your-rights-flyer-oek-ontheemden-ru.pdf), Document:
However, the IND still sees Ukraine as an unsafe country of origin.\n\n*Therefore, Ukrainians who have received a
negative decision do not have to return.\n\n*   \n\nFor more information, see:
https://ind.nl/en/ukraine/temporarily-no-decisions-on-asylum-applications-ukrainians  Please note: when Ukrainian
people apply for asylum, they follow the standard procedure and have the same rights as other asylum seekers:
https://www.coa.nl/en.\n\nThe only difference is that they know in advance that at least until 28 November 2023 +
21 months no decision will be taken on their status.   \n\nPlease note: if you follow the standard asylum
procedure, you can only do paid work for 24 weeks per year if you don't have a residence permit yet.  \n\nEmployers
must have a work permit for third-country nationals (TWV) to employ asylum seekers.\n\nThe Employee Insurance
Agency (UWV) will issue this permit if an asylum application process has lasted at least 6 months.\n\nFor more
information see: https://www.coa.nl/en/work, Document: Flyer about (healthcare during) pregnancy Flyer about
(healthcare during) pregnancy in Ukrainian and Englis:
https://assets.ctfassets.net/496uch1l97fc/2KF2tVsvf4WhqVUuSYS91s/9fe1a79f178ec9ef6a814fa85389b19c/Folder-geboortezo
rg-Oekraiens-Nederlands-CPZ-14-juni-2022-1.pdf, Document: - Are you being forced to do work against your will?
\n\n1.\n\nIf the situation does not seem urgent, send the contact information of FairWork as well as the flyer
below.  \n\n2.\n\nIf the situation is serious and needs a follow up, you can make a warm referral: ask for
permission to share the phone number of the PA with FairWork, so that the organisation can reach out to the PA
directly.\n\nExplain to the PA what FairWork does and that someone from the organisation will reach out to them in
the following days.\n\n3.\n\nIf the situation needs immediate attention, inform the TC and they will call FairWork
themselves to request help for the PA immediately.  \n\nhttps://www.fairwork.nu/en/homepage/  Phone: +31 20 760 08
09  FairWork and the Red Cross have produced flyers about working in the Netherlands for displaced persons from
Ukraine: - [English](https://www.comensha.nl/media/jizlbk4d/2026-know-your-rights-flyer-oek-ontheemden-eng.pdf) -,
Document: A twv is required if you want to work as a self-employed person.  \n\nStarting on 1 April 2022, employers
must notify the Employee Insurance Agency (in Dutch: UWV)  that they are employing someone.  \n\nFor most recent
information see:  -
https://ind.nl/en/ukraine/temporary-protection-directive-ukraine#working-and-studying-in-the-netherlands -
https://www.government.nl/topics/reception-of-refugees-from-ukraine/work-and-income -
https://www.refugeehelp.nl/en/ukrainian-refugee/article/100149-conditions-for-working-in-the-netherlands, Document:
I have a problem at work and/or I don't feel safe while working or there is labour exploitation.\n\nWhat should I
do?\n\nIt’s very important for you to know your rights and feel secure in any situation.\n\nDo you need help or are
you unsure about your work?\n\nAre you worried about someone else?    \n\nOpora (https://www.oporafoundation.nl/)
provides juridical information to displaced persons from Ukraine on topics related to work.\n\nWe can refer you to
Opora in case you have questions about: - Labor contracts - Pension - Child allowance   FairWork works together
with Opora.   \n\nFairWork is specialized in helping people who have problems at work and/or people who are
affected by labour exploitation or human trafficking.\n\nIf the PA shows signs of labour exploitation/human
trafficking, you can ask the following questions:  - Can you tell me more about your work environment?  \n\n-Are
the work conditions as you expected?\n\n- Do you feel safe at work?\n\n- Does your employer treat you badly?\n\n-
Are you being forced to do work against your will?  \n\n1., Document: How long can I stay away from the
shelter?\n\nUkrainians may leave reception for 14 days in a calander year with retention of the reception place and
28 days in a calander year with retention of living allowance.\n\nFor example, for holidays, family visits or a
funeral.\n\nIt depends on the municipality how strictly this is enforced.\n\nThe PA must always report his or her
departure to a reception staff member.\n\nIf the PA does not report the departure but leaves longer than 28 days,
they can lose the reception place and the municipality can stop the living allowance immediately., Document:
Alternatively, you may apply for international protection.\n\n- Stateless persons and nationals of third countries
residing legally in Ukraine on a short-term basis before 24 February 2022, such as students and workers.
\n\nHowever, the rules applied vary per EU country.\n\nYou can find a detailed overview of country specific rules
and updates on this website:
https://www.fragomen.com/insights/european-unionukraine-temporary-protection-status-country-specific-updates.html
Please check what the rules are for third country nationals for the country you want to go to., Document: What do I
need to do when I leave the Netherlands?  \n\nBefore you leave you must (if relevant): - deregister from your
municipality (Personal Records Database (BRP)); - inform your employer that you are leaving; - inform your school
that you are leaving;  - close your bank account.   \n\nAssistance with returning to your country of origin: If you
wish to receive assistance, register with the Repatriation and Departure Service (DT&V).\n\nDT&V can help you
arrange your journey to your country of origin or another country outside the EU where you are permitted to stay
for a longer period., Document: How long can I stay away from the shelter?\n\nA displaced person may leave
reception for 14 days with retention of the reception place and 28 days with retention of living allowance.\n\nFor
example, for holidays, family visits or a funeral.\n\nThe displaced person must always report his or her departure
to a reception staff member.\n\nIf the displaced person does not report the departure, they can lose the reception
place immediately and the municipality can stop the living allowance immediately., Document: IOM (International
Office of Migrants)\n\nYou can contact IOM via phone (+)31 88 746 44 66 for questions regarding voluntary
return.\n\nYou can also contact IOM via whatsapp between 9:00 and 17:00 here: (https://wa.me/31682091550)  on
Monday, Tuesday, Wednesday and Thursday.\n\nOr here: (https://wa.me/31682091228) on Monday, Tuesday, Thursday and
Friday., Document: - Go to the exit or a central safe place designated for this purpose.   \n\n- Follow the
instructions of the staff.   \n\n- If the alarm goes off, always leave the building.   \n\n- Everyone gathers
outside at the designated assembly point.\n\nAsk someone at the site where the assembly point is if you don't know.
\n\nSource and more information: https://www.mycoa.nl/en/the-netherlands/dangers-in-nature/wildfires, Document: Can
I travel to Ukraine without losing the temporary protection status?   \n\nUkrainians who already have a temporary
protection and have an urgent reason can travel to Ukraine for urgent matters, such as picking up relatives,
transporting belongings, or medical issues, and return to the Netherlands within a few days or weeks.\n\nHowever,
if you stay in Ukraine or another country for an extended period, the IND may look whether you still qualify for
temporary protection.\n\nWhile your status won’t be automatically revoked, you must provide a valid reason for your
long absence.  \n\nImportant note: If you live in a shelter you may leave the shelter for 14 days per calander year
with retention of the reception place and 28 days per calander year with retention of living allowance.\n\nThe
displaced person must always report his or her departure to a reception staff member.\n\nIf the displaced person
does not report the departure, they can lose the reception place immediately and the municipality can stop the
living allowance immediately.\n\nIf you don't live in a shelter, it is still good to always report to the
municipality that you are going to Ukraine for a period of time., Document: Flyer about human trafficking and
exploitation Download the Red Cross flyer with information about labour rights, risks of exploitation and
organizations that can help.\n\nThis is available in
[English](https://www.comensha.nl/media/p2bnzsr3/dec2023_nrk_flyer_know_your_rights_oek_en.pdf),
[Ukrainian](https://www.comensha.nl/media/ju4hmw0h/dec2023_nrk_flyer_know_your_rights_oek_oek.pdf) and
[Russian](https://www.comensha.nl/media/vznlob3l/dec2023_nrk_flyer_know_your_rights_oek_ru.pdf), Document: What
should I do if I return to the Netherlands after a period in Ukraine (or another country)?\n\nWhat to do on return:
- When you return to the Netherlands, you must report again to the municipality or municipal reception center where
you previously stayed.\n\n- If you have lost your shelter place as a result of the earlier (temporary) departure
and the living allowance has been stopped, it will be assessed whether you comply with the applicable rules at the
time of your return.\n\nIf this is the case, you are again entitled to childcare and the other benefits in kind
from the ROOO.\n\n- If you have been deregistered from the BRP, registration must be done again.   \n\nWhat to do
with earlier advice on a shelter location in case of temporary departure: - At the moment, municipalities are
advised to maintain a shelter for displaced persons who leave the municipal shelter for less than 14 days.\n\n-
This advice was issued mid-2022 and remains valid.\n\nIn case of a departure of more than 14 days, the municipality
can give the reception place to someone else, for example if the occupancy rate is high., Document: Can I work in
The Netherlands?  \n\nEveryone who comes under the Temporary Protection Directive can work in the Netherlands
without a work permit (in Dutch: tewerkstellingsvergunning or twv).\n\nThis means that an employer does not have to
request a work permit for you.\n\nAnd that you can easily look for a job, if you want to.   \n\nThe work permit
exemption applies to all work in employment.\n\nYou will need an employment contract with an employer.\n\nYou must
also meet the following requirements:  - You come under the Temporary Protection Directive.\n\nWe advise you to
register at the local council if you come under the directive.  \n\n- You have proof of residency showing that you
are allowed to be in the Netherlands.\n\nAs proof, you will receive a sticker or card from the IND.  \n\nThe
requirements for the exemption also apply if want to work as a volunteer.\n\nThe organisation where you want to
work must then request a volunteer declaration from the UWV.\n\nYou may also work as a trainee, when you, your
employer and your school have signed a trainee contract.\n\nA twv is required if you want to work as a
self-employed person., Document: 3.\n\nIf PA is still abroad and planning to come to NL, ask PA to check on the
situation right before departure.\n\nThey can get in touch with us for that.\n\nThe advice is also for PA to check
the TP rules in other countries on the way to NL, should they decide to request TP and shelter there.  \n\n4.\n\nIf
PA is asking if men are still accepted in NL under TP, the answer is yes.\n\nHowever, unfortunatly due to limited
availability, it is more difficult for single, adult men to get shelter.\n\nWomen, children and people with medical
indications have priority.\n\nThis is something to take into account.   \n\nAlways try to check if a PA is
vulnerable and falls under on of the following categories:  - 67+ years old - Families with children - Single minor
(under 18) -\n\nExtra care (wheelchair, handicap, etc.) - Pregant woman - LHBTQI++  Actions to take when general
advice is not sufficient Consult with TC and/or  refer the case to the TC., Document: Am I covered by the Temporary
Protection Directive if I had a work visa for another EU country?\n\nIt is important to always check when the PA
got his/her work visa and for which country.   \n\n- Work visa before 27.11.2021: Refugees from Ukraine who were
working or studying in another European Union country before 27 November 2021 are not entitled to
reception.\n\nCheck whether you are covered in the country that issued your visa.  \n\n- Work visa after
26.11.2021: If you left Ukraine after 26.11.2021 to another EU country to work and your work visa expires, you may
be entitled for Temporary Protection in the Netherlands.\n\nAlways ask what kind of work visa the PA has and verify
that it really is a work visa, not a permanent visa.\n\nIf PA has an expired work visa and he is eligible for
temporary protection in the Netherlands, always explain the current situation in the Netherlands concerning housing
and ask if PA cannot stay in the country he already is in., Document: What are my options for staying in/leaving
the Netherlands?\n\nYou can find a few options for you after your protection status changes below, Document: Can I
stay in the public shelter while I have a paid job?  \n\nDisplaced persons from Ukraine that are doing paid work
may remain at the municipal reception centre.\n\nHowever, you will have to pay a contribution.\n\nYou can also move
to other accommodation, for instance with a host family, friends or family members, or at a hotel.  \n\nFor most
recent information see: https://www.government.nl/topics/reception-of-refugees-from-ukraine/work-and-income]
16
[Document: Remaining Undocumented If you remain in the Netherlands without residency status you will become
*undocumented*.\n\nUndocumented persons do not have a right to housing, work or government subsidies.\n\nHowever,
you still have the right to necesarry medical care, judicial assistance and children under 18 have to right to
attend school as well.  \n\nYou can choose to apply for asylum at any point with undocumented status.  \n\nFor more
information you can reach out to the Red Cross helpline via Whatsapp here: https://wa.me/31614458781 or visit the
Red Cross website Helpful Information: https://helpfulinformation.redcross.nl/, Document: Amsterdam (e-mail
!)\n\nHSP is closed Ukrainians in Amsterdam can report to the municipality directly via opvangoekraine@amsterdam.nl
\n\nSometimes, the person may initially receive a rejection due to the current situation in NL.\n\nWe recommend
following up on the response and continuing communication with the municipality via the same email.\n\nIn your
follow-up, kindly explain your situation, where you're staying, and how long you can stay there.\n\nAlso, include
any important details about your circumstances, such as medical conditions, young children, or other special needs,
Document: GGD Center for Sexual Health in Amsterdam You can talk to the GGD about every topic concerning your body,
your relations and sex.\n\nThey can provide care regarding your sexual health, sexual orientation, gender issues,
sexwork or sexual violence.\n\nCome in to talk about ways to protect yourself with  PEP/PrEP, contraception and
vaccinations.\n\nThis is a LHBT-friendly centre.\n\nYou don't need  ID / BSN / health-insurance.  \n\nYou have to
call or use the website link to make an appointment.   \n\nEveryone is welcome, the care is free of charge.\n\nYou
do not need a referral by a doctor.   \n\nAll healthcare workers have professional secrecy.
\n\nhttps://afspraak.ggdaphrodite.nl/?lang=en   Phone: (020) 555 5822  Address: GGD Amsterdam Centrum voor Seksuele
Gezondheid Nieuwe Achtergracht 100 1018 WT Amsterdam (near Weesperplein metro station), Document: I am a
transperson, where can I get support?\n\nIf you need trans care, you can contact the Trans United trans clinic, a
community initiative with support from the GGD Amsterdam:  https://transunitedeurope.eu/?page_id=255  \n\nFor more
information see:  -
https://www.refugeehelp.nl/en/ukrainian-refugee/article/100298-living-in-the-netherlands-as-an-lgbtqia-individual -
https://www.refugeehelp.nl/en/ukrainian-refugee/article/100299-activities-for-the-lgbtqia-community, Document: I
need medical treatment in the Netherlands and an I am abroad  Many people in Ukraine lack access to the medical
care they need.\n\nThis can be for all kinds of diseases, like cancer treatment, but also for wounds caused by
grenades, bullets or mines.   \n\nFor a detailed step-by-step guide on handling cases where PAs abroad want to come
to the Netherlands, see below.  \n\n## Important notes  - There are two main categories of people wanting to come
to NL for medical treatment.\n\nAlways ask the PA about their goal of coming to the Netherlands:  1.\n\nComing to
the Netherlands for temporary treatment and then returning to Ukraine: Since the start of the war, the EU has
designed a standard procedure for Ukrainians in need of urgent medical care.\n\nThe patients must be applied by
their doctor for one of the following programs: Medevac Coordination Center (Civil) or Medical Forces Command
(Military).\n\nEU countries (NL included) will receive these applications and can decide to accept the case, after
which the patient will be brought to a medical hub in Poland and then transferred to the country that accepted.,
Document: I need medical treatment and I am in the Netherlands.\n\nWhat can I do?  \n\nAll hospitals in the
Netherlands provide medical care for Ukrainian refugees, including Ukrainian PAs with cancer.\n\nThey can continue
their treatment in the Netherlands, in consultation with a doctor. \r \n\nFirst, you need to visit a general
practitioner (GP), who will refer you to the hospital if necessary.\n\nIf you have your medical file, bring it with
you as it can be helpful.\n\nHaving a Dutch-speaking person assist you can also make the process easier, but it is
not mandatory.   \n\nFor more information on finding a GP, see the questions under the sub-category 'doctor' or
click (https://agreeable-forest-090d2f903.4.azurestaticapps.net/ukraine/health-wellbeing/doctor) \r \n\nFor most
recent information on cancer treatment see:
https://www.kanker.nl/nieuwsberichten/gratis-kankerzorg-voor-oekraiense-vluchtelingen, Document: Netherlands Red
Cross Amsterdam Every person in need, regardless of background and papers, is welcome at the Humanitarian Service
Point in the Amsterdam office of The Netherlands Red Cross.\n\nFor everyone who visits, the situation is examined

After assesing the LLM reasoning, I decided to agree and flip row 11 from fail to pass. Therefore, we must recalculate. However, for row 16, DeepEval was too lenient, as a big portion of the retrieved contexts (such as information about sexual health) is irrelevant to a user who has already been redirected by the bot regarding medical procedures.

In [118]:
merged.loc[11, 'context_relevancy_label'] = 1 # general change
cr_labelled.loc[11, 'context_relevancy_label'] = 1 # to reflect the change in the labelled dataframe

#  Pass rate (from labels)
my_pass_rate = (cr_labelled["context_relevancy_label"] == 1).mean()

# DeepEval's pass rate (at default threshold)
deepeval_pass_rate = (cr_labelled["Contextual Relevancy"] >= threshold).mean()

print(f"My pass rate: {my_pass_rate:.2%}")
print(f"DeepEval pass rate at threshold {threshold}: {deepeval_pass_rate:.2%}")

My pass rate: 23.08%

DeepEval pass rate at threshold 0.5: 30.77%

### Applying the percentile method with target

In [145]:
scores = cr_labelled["Contextual Relevancy"].tolist()
sorted_scores = sorted(scores)
print(sorted_scores)

[
    0.016,
    0.16129032258064516,
    0.24271844660194175,
    0.31443298969072164,
    0.391304347826087,
    0.39344262295081966,
    0.3968253968253968,
    0.4146341463414634,
    0.48,
    0.5483870967741935,
    0.797979797979798,
    0.8691588785046729,
    0.8699186991869918
]

In [146]:
index = int(len(sorted_scores) * (1 - context_relevancy_percentile / 100))

In [147]:
index

11

This gives the 11th-lowest score (out of 13) as the threshold. Only scores above the 10th-lowest pass.

In [148]:
print(f"Threshold for {context_relevancy_percentile:.2f}% percentile: {sorted_scores[index]:.2f}")

Threshold for 15.38% percentile: 0.87

In [124]:
# Sanity check
cr_labelled["de_predicted"] = cr_labelled["Contextual Relevancy"] >= 0.87
print(cr_labelled[["input", "Contextual Relevancy", "context_relevancy_label", "de_predicted"]])

C:\Users\dari\AppData\Local\Temp\ipykernel_39000\946920461.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cr_labelled["de_predicted"] = cr_labelled["Contextual Relevancy"] >= 0.87

           input  \
8
I'm homeless and looking for a shelter. I am very tired. I don't have anyone to help me.
9
You already told me about the day shelters. I know about those. I need an actual place to sleep tonight with my
children. Stop giving me the same information!
10
live in Utrecht, but I got kicked out of my house today. Where can I find a warm meal?
11  I am from Ukraine and I work in a factory. I live with my other colleagues, and my boss pays for my rent,
utilities, and gives me an allowance. I want to go home this Christmas to visit my family, but he refuses because
he says it's the busiest season and if I leave everyone will want to go home as well, so we will all lose our jobs.
Can you help somehow?
12
My family and I got denied access to the shelter. We are from Ukraine and we are in Rotterdam right now. We are
very tired.
13
wer find winter clodes. I nigeria.
14
I am from Morocco and I have been living in the Netherlands for 20 years. My doctor retired and the new practice is
refusing to register me because I don't have a BSN. I know my rights, and this is incredibly frustrating. What else
can I do?
15
I have diabetes and I am undocumented. I need insulin but I also cannot afford the food I need for my diet. The
doctor told me I need to eat differently but everything is too expensive.
16
I have been to 3 hospitals, but they refuse me because I am undocumented. I am in immense pain and need immediate
attention. I am in Amsterdam. What do I do?
17
I have a temporary residence permit from Portugal, but I am originally from Iraq. I moved to the Netherlands to
find work, but now they are telling me I cannot work here. I don’t understand. I have European papers.
18                                                                           I live in Utrecht and I am on the
streets now because of an abusive landlord. I went to a homeless shelter with my children and they refused me
because I still have my job and some saved up money, but not enough for a hotel. Now they are threatening to take
my children away. Help me!
19
I am undocumented and I have two children. They need to go to school but I am afraid to register them. Also, where
can I get winter clothes for them? They are growing fast
20
I lost my job and got kicked out of my house because I could not pay rent. I am from Poland. I have been homeless
for a couple of days, and need to shower and do laundry.

    Contextual Relevancy  context_relevancy_label  de_predicted
8               0.869919                      1.0         False
9               0.480000                      0.0         False
10              0.161290                      0.0         False
11              0.869159                      1.0         False
12              0.797980                      1.0         False
13              0.016000                      0.0         False
14              0.396825                      0.0         False
15              0.242718                      0.0         False
16              0.548387                      0.0         False
17              0.414634                      0.0         False
18              0.391304                      0.0         False
19              0.314433                      0.0         False
20              0.393443                      0.0         False

Most of rows that failed sit just below 0.87, therefore we adjust the threshold to 0.86.

In [125]:
cr_labelled["de_predicted"] = cr_labelled["Contextual Relevancy"] >= 0.86
print(cr_labelled[["input", "Contextual Relevancy", "context_relevancy_label", "de_predicted"]])

C:\Users\dari\AppData\Local\Temp\ipykernel_39000\4215209069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cr_labelled["de_predicted"] = cr_labelled["Contextual Relevancy"] >= 0.86

           input  \
8
I'm homeless and looking for a shelter. I am very tired. I don't have anyone to help me.
9
You already told me about the day shelters. I know about those. I need an actual place to sleep tonight with my
children. Stop giving me the same information!
10
live in Utrecht, but I got kicked out of my house today. Where can I find a warm meal?
11  I am from Ukraine and I work in a factory. I live with my other colleagues, and my boss pays for my rent,
utilities, and gives me an allowance. I want to go home this Christmas to visit my family, but he refuses because
he says it's the busiest season and if I leave everyone will want to go home as well, so we will all lose our jobs.
Can you help somehow?
12
My family and I got denied access to the shelter. We are from Ukraine and we are in Rotterdam right now. We are
very tired.
13
wer find winter clodes. I nigeria.
14
I am from Morocco and I have been living in the Netherlands for 20 years. My doctor retired and the new practice is
refusing to register me because I don't have a BSN. I know my rights, and this is incredibly frustrating. What else
can I do?
15
I have diabetes and I am undocumented. I need insulin but I also cannot afford the food I need for my diet. The
doctor told me I need to eat differently but everything is too expensive.
16
I have been to 3 hospitals, but they refuse me because I am undocumented. I am in immense pain and need immediate
attention. I am in Amsterdam. What do I do?
17
I have a temporary residence permit from Portugal, but I am originally from Iraq. I moved to the Netherlands to
find work, but now they are telling me I cannot work here. I don’t understand. I have European papers.
18                                                                           I live in Utrecht and I am on the
streets now because of an abusive landlord. I went to a homeless shelter with my children and they refused me
because I still have my job and some saved up money, but not enough for a hotel. Now they are threatening to take
my children away. Help me!
19
I am undocumented and I have two children. They need to go to school but I am afraid to register them. Also, where
can I get winter clothes for them? They are growing fast
20
I lost my job and got kicked out of my house because I could not pay rent. I am from Poland. I have been homeless
for a couple of days, and need to shower and do laundry.

    Contextual Relevancy  context_relevancy_label  de_predicted
8               0.869919                      1.0          True
9               0.480000                      0.0         False
10              0.161290                      0.0         False
11              0.869159                      1.0          True
12              0.797980                      1.0         False
13              0.016000                      0.0         False
14              0.396825                      0.0         False
15              0.242718                      0.0         False
16              0.548387                      0.0         False
17              0.414634                      0.0         False
18              0.391304                      0.0         False
19              0.314433                      0.0         False
20              0.393443                      0.0         False

Final threshold: 0.86.

## Faithfulness

In [126]:
# Extract the labelling column
label = merged["faithfulness_label"]

# Calculate the percentage of entries with faithfulness_label = 1
count = 0
for val in label:
    if val == 1:
        count += 1
total_entries = merged["retrieval_context"].apply(has_context).sum()
print(f"Total number of entries (answers with context chunks): {total_entries}")
faithfulness_percentile = (count / total_entries) * 100

print(f"Percentage of entries with faithfulness_label = 1 from manual annotation: {faithfulness_percentile:.2f}%")

Total number of entries (answers with context chunks): 13

Percentage of entries with faithfulness_label = 1 from manual annotation: 92.31%

In [79]:
cols_to_display = ["input", "bot_output", "retrieval_context", "Faithfulness", "Faithfulness_reason", "faithfulness_label"]
faith = merged[cols_to_display]

In [155]:
threshold = 0.5  # DeepEval default
faith_labelled = faith[faith["faithfulness_label"].notna()] # to not catch NaN-labelled rows as mismatches

# Pass rate (from labels)
my_pass_rate = (faith_labelled["faithfulness_label"] == 1).mean()

# DeepEval's pass rate (at default threshold)
deepeval_pass_rate = (faith_labelled["Faithfulness"] >= threshold).mean()

print(f"My pass rate: {my_pass_rate:.2%}")
print(f"DeepEval pass rate at threshold {threshold}: {deepeval_pass_rate:.2%}")

My pass rate: 92.31%

DeepEval pass rate at threshold 0.5: 100.00%

### Do we agree on which instances pass and which fail?

Passing labels

In [84]:
labelled = faith[faith['faithfulness_label'].notna()] # to not catch NaN-labelled rows as mismatches
print(f"Passing rows (my labels): {labelled[labelled['faithfulness_label'] == 1].index.tolist()}")
print(f"Passing rows (Deep Eval): {labelled[labelled['Faithfulness'] >= threshold].index.tolist()}")
print(f"Rows which don't don't match: {labelled[(labelled['faithfulness_label'] == 1) !=(labelled['Faithfulness'] >= threshold)].index.tolist()}")

Passing rows (my labels): [8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Passing rows (Deep Eval): [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Rows which don't don't match: [11]

In [83]:
non_matches = labelled[(labelled['faithfulness_label'] == 1) != (labelled['Faithfulness'] >= threshold)].index
print(f"Non-matching rows (Rows I matched as non-faithful): {faith.loc[non_matches, ['input','bot_output', 'retrieval_context', 'Faithfulness', 'Faithfulness_reason' ]]}")

Non-matching rows (Rows I matched as non-faithful):
input  \
11  I am from Ukraine and I work in a factory. I live with my other colleagues, and my boss pays for my rent,
utilities, and gives me an allowance. I want to go home this Christmas to visit my family, but he refuses because
he says it's the busiest season and if I leave everyone will want to go home as well, so we will all lose our jobs.
Can you help somehow?













                                           bot_output  \
11  Hello! I am Aidly, the HIA chatbot.\n\nFrom the information available, as a displaced person from Ukraine
working in the Netherlands, you have the same labour rights as Dutch employees, including the right to a safe
working space and fair treatment. Your employer should not force you to work against your will or prevent you from
taking reasonable time off, such as for family visits during holidays.\n\nIf your employer is refusing to allow you
to visit your family for Christmas and you feel pressured or unsafe, you can seek help. There are organizations
like FairWork that specialize in helping people with work problems or labour exploitation. You can contact FairWork
at +31 20 760 08 09 or visit https://www.fairwork.nu/en/homepage/ for assistance.\n\nAlso, you can share with your
employer the flyer "Know your rights when you work," available in English and Ukrainian, to inform them about your
rights: https://www.comensha.nl/media/jizlbk4d/2026-know-your-rights-flyer-oek-ontheemden-eng.pdf\n\nIf the
situation is urgent or you feel forced to work against your will, you can ask for immediate help through
FairWork.\n\nRemember, you should also report your departure if you live in a shelter, but since you live with
colleagues and your boss pays rent, make sure to inform the relevant reception or municipality if applicable.\n\nIf
you want, I can help you find more detailed advice or contacts. Would you like that?





























































































































      retrieval_context  \
11  [Document: What are my working rights when I work in the Netherlands?\n\nDisplaced Ukrainians have the same
labour rights as Dutch employees.\n\nThese rights include a safe working space, regular breaks, and the
minimumwage.   \n\nFor questions about labour rights you can share the flyer 'Know your rights when you work' with
the person affected.\n\nFor Ukrainian people this is available in:
-\n\n[English](https://www.comensha.nl/media/jizlbk4d/2026-know-your-rights-flyer-oek-ontheemden-eng.pdf)
-\n\n[Ukrainian](https://www.comensha.nl/media/kdcfdy13/2026-know-your-rights-flyer-oek-ontheemden-oek.pdf) -
[Russian](https://www.comensha.nl/media/fbtnesz5/2026-know-your-rights-flyer-oek-ontheemden-ru.pdf), Document:
However, the IND still sees Ukraine as an unsafe country of origin.\n\n*Therefore, Ukrainians who have received a
negative decision do not have to return.\n\n*   \n\nFor more information, see:
https://ind.nl/en/ukraine/temporarily-no-decisions-on-asylum-applications-ukrainians  Please note: when Ukrainian
people apply for asylum, they follow the standard procedure and have the same rights as other asylum seekers:
https://www.coa.nl/en.\n\nThe only difference is that they know in advance that at least until 28 November 2023 +
21 months no decision will be taken on their status.   \n\nPlease note: if you follow the standard asylum
procedure, you can only do paid work for 24 weeks per year if you don't have a residence permit yet.  \n\nEmployers
must have a work permit for third-country nationals (TWV) to employ asylum seekers.\n\nThe Employee Insurance
Agency (UWV) will issue this permit if an asylum application process has lasted at least 6 months.\n\nFor more
information see: https://www.coa.nl/en/work, Document: Flyer about (healthcare during) pregnancy Flyer about
(healthcare during) pregnancy in Ukrainian and Englis:
https://assets.ctfassets.net/496uch1l97fc/2KF2tVsvf4WhqVUuSYS91s/9fe1a79f178ec9ef6a814fa85389b19c/Folder-geboortezo
rg-Oekraiens-Nederlands-CPZ-14-juni-2022-1.pdf, Document: - Are you being forced to do work against your will?
\n\n1.\n\nIf the situation does not seem urgent, send the contact information of FairWork as well as the flyer
below.  \n\n2.\n\nIf the situation is serious and needs a follow up, you can make a warm referral: ask for
permission to share the phone number of the PA with FairWork, so that the organisation can reach out to the PA
directly.\n\nExplain to the PA what FairWork does and that someone from the organisation will reach out to them in
the following days.\n\n3.\n\nIf the situation needs immediate attention, inform the TC and they will call FairWork
themselves to request help for the PA immediately.  \n\nhttps://www.fairwork.nu/en/homepage/  Phone: +31 20 760 08
09  FairWork and the Red Cross have produced flyers about working in the Netherlands for displaced persons from
Ukraine: - [English](https://www.comensha.nl/media/jizlbk4d/2026-know-your-rights-flyer-oek-ontheemden-eng.pdf) -,
Document: A twv is required if you want to work as a self-employed person.  \n\nStarting on 1 April 2022, employers
must notify the Employee Insurance Agency (in Dutch: UWV)  that they are employing someone.  \n\nFor most recent
information see:  -
https://ind.nl/en/ukraine/temporary-protection-directive-ukraine#working-and-studying-in-the-netherlands -
https://www.government.nl/topics/reception-of-refugees-from-ukraine/work-and-income -
https://www.refugeehelp.nl/en/ukrainian-refugee/article/100149-conditions-for-working-in-the-netherlands, Document:
I have a problem at work and/or I don't feel safe while working or there is labour exploitation.\n\nWhat should I
do?\n\nIt’s very important for you to know your rights and feel secure in any situation.\n\nDo you need help or are
you unsure about your work?\n\nAre you worried about someone else?    \n\nOpora (https://www.oporafoundation.nl/)
provides juridical information to displaced persons from Ukraine on topics related to work.\n\nWe can refer you to
Opora in case you have questions about: - Labor contracts - Pension - Child allowance   FairWork works together
with Opora.   \n\nFairWork is specialized in helping people who have problems at work and/or people who are
affected by labour exploitation or human trafficking.\n\nIf the PA shows signs of labour exploitation/human
trafficking, you can ask the following questions:  - Can you tell me more about your work environment?  \n\n-Are
the work conditions as you expected?\n\n- Do you feel safe at work?\n\n- Does your employer treat you badly?\n\n-
Are you being forced to do work against your will?  \n\n1., Document: How long can I stay away from the
shelter?\n\nUkrainians may leave reception for 14 days in a calander year with retention of the reception place and
28 days in a calander year with retention of living allowance.\n\nFor example, for holidays, family visits or a
funeral.\n\nIt depends on the municipality how strictly this is enforced.\n\nThe PA must always report his or her
departure to a reception staff member.\n\nIf the PA does not report the departure but leaves longer than 28 days,
they can lose the reception place and the municipality can stop the living allowance immediately., Document:
Alternatively, you may apply for international protection.\n\n- Stateless persons and nationals of third countries
residing legally in Ukraine on a short-term basis before 24 February 2022, such as students and workers.
\n\nHowever, the rules applied vary per EU country.\n\nYou can find a detailed overview of country specific rules
and updates on this website:
https://www.fragomen.com/insights/european-unionukraine-temporary-protection-status-country-specific-updates.html
Please check what the rules are for third country nationals for the country you want to go to., Document: What do I
need to do when I leave the Netherlands?  \n\nBefore you leave you must (if relevant): - deregister from your
municipality (Personal Records Database (BRP)); - inform your employer that you are leaving; - inform your school
that you are leaving;  - close your bank account.   \n\nAssistance with returning to your country of origin: If you
wish to receive assistance, register with the Repatriation and Departure Service (DT&V).\n\nDT&V can help you
arrange your journey to your country of origin or another country outside the EU where you are permitted to stay
for a longer period., Document: How long can I stay away from the shelter?\n\nA displaced person may leave
reception for 14 days with retention of the reception place and 28 days with retention of living allowance.\n\nFor
example, for holidays, family visits or a funeral.\n\nThe displaced person must always report his or her departure
to a reception staff member.\n\nIf the displaced person does not report the departure, they can lose the reception
place immediately and the municipality can stop the living allowance immediately., Document: IOM (International
Office of Migrants)\n\nYou can contact IOM via phone (+)31 88 746 44 66 for questions regarding voluntary
return.\n\nYou can also contact IOM via whatsapp between 9:00 and 17:00 here: (https://wa.me/31682091550)  on
Monday, Tuesday, Wednesday and Thursday.\n\nOr here: (https://wa.me/31682091228) on Monday, Tuesday, Thursday and
Friday., Document: - Go to the exit or a central safe place designated for this purpose.   \n\n- Follow the
instructions of the staff.   \n\n- If the alarm goes off, always leave the building.   \n\n- Everyone gathers
outside at the designated assembly point.\n\nAsk someone at the site where the assembly point is if you don't know.
\n\nSource and more information: https://www.mycoa.nl/en/the-netherlands/dangers-in-nature/wildfires, Document: Can
I travel to Ukraine without losing the temporary protection status?   \n\nUkrainians who already have a temporary
protection and have an urgent reason can travel to Ukraine for urgent matters, such as picking up relatives,
transporting belongings, or medical issues, and return to the Netherlands within a few days or weeks.\n\nHowever,
if you stay in Ukraine or another country for an extended period, the IND may look whether you still qualify for
temporary protection.\n\nWhile your status won’t be automatically revoked, you must provide a valid reason for your
long absence.  \n\nImportant note: If you live in a shelter you may leave the shelter for 14 days per calander year
with retention of the reception place and 28 days per calander year with retention of living allowance.\n\nThe
displaced person must always report his or her departure to a reception staff member.\n\nIf the displaced person
does not report the departure, they can lose the reception place immediately and the municipality can stop the
living allowance immediately.\n\nIf you don't live in a shelter, it is still good to always report to the
municipality that you are going to Ukraine for a period of time., Document: Flyer about human trafficking and
exploitation Download the Red Cross flyer with information about labour rights, risks of exploitation and
organizations that can help.\n\nThis is available in
[English](https://www.comensha.nl/media/p2bnzsr3/dec2023_nrk_flyer_know_your_rights_oek_en.pdf),
[Ukrainian](https://www.comensha.nl/media/ju4hmw0h/dec2023_nrk_flyer_know_your_rights_oek_oek.pdf) and
[Russian](https://www.comensha.nl/media/vznlob3l/dec2023_nrk_flyer_know_your_rights_oek_ru.pdf), Document: What
should I do if I return to the Netherlands after a period in Ukraine (or another country)?\n\nWhat to do on return:
- When you return to the Netherlands, you must report again to the municipality or municipal reception center where
you previously stayed.\n\n- If you have lost your shelter place as a result of the earlier (temporary) departure
and the living allowance has been stopped, it will be assessed whether you comply with the applicable rules at the
time of your return.\n\nIf this is the case, you are again entitled to childcare and the other benefits in kind
from the ROOO.\n\n- If you have been deregistered from the BRP, registration must be done again.   \n\nWhat to do
with earlier advice on a shelter location in case of temporary departure: - At the moment, municipalities are
advised to maintain a shelter for displaced persons who leave the municipal shelter for less than 14 days.\n\n-
This advice was issued mid-2022 and remains valid.\n\nIn case of a departure of more than 14 days, the municipality
can give the reception place to someone else, for example if the occupancy rate is high., Document: Can I work in
The Netherlands?  \n\nEveryone who comes under the Temporary Protection Directive can work in the Netherlands
without a work permit (in Dutch: tewerkstellingsvergunning or twv).\n\nThis means that an employer does not have to
request a work permit for you.\n\nAnd that you can easily look for a job, if you want to.   \n\nThe work permit
exemption applies to all work in employment.\n\nYou will need an employment contract with an employer.\n\nYou must
also meet the following requirements:  - You come under the Temporary Protection Directive.\n\nWe advise you to
register at the local council if you come under the directive.  \n\n- You have proof of residency showing that you
are allowed to be in the Netherlands.\n\nAs proof, you will receive a sticker or card from the IND.  \n\nThe
requirements for the exemption also apply if want to work as a volunteer.\n\nThe organisation where you want to
work must then request a volunteer declaration from the UWV.\n\nYou may also work as a trainee, when you, your
employer and your school have signed a trainee contract.\n\nA twv is required if you want to work as a
self-employed person., Document: 3.\n\nIf PA is still abroad and planning to come to NL, ask PA to check on the
situation right before departure.\n\nThey can get in touch with us for that.\n\nThe advice is also for PA to check
the TP rules in other countries on the way to NL, should they decide to request TP and shelter there.  \n\n4.\n\nIf
PA is asking if men are still accepted in NL under TP, the answer is yes.\n\nHowever, unfortunatly due to limited
availability, it is more difficult for single, adult men to get shelter.\n\nWomen, children and people with medical
indications have priority.\n\nThis is something to take into account.   \n\nAlways try to check if a PA is
vulnerable and falls under on of the following categories:  - 67+ years old - Families with children - Single minor
(under 18) -\n\nExtra care (wheelchair, handicap, etc.) - Pregant woman - LHBTQI++  Actions to take when general
advice is not sufficient Consult with TC and/or  refer the case to the TC., Document: Am I covered by the Temporary
Protection Directive if I had a work visa for another EU country?\n\nIt is important to always check when the PA
got his/her work visa and for which country.   \n\n- Work visa before 27.11.2021: Refugees from Ukraine who were
working or studying in another European Union country before 27 November 2021 are not entitled to
reception.\n\nCheck whether you are covered in the country that issued your visa.  \n\n- Work visa after
26.11.2021: If you left Ukraine after 26.11.2021 to another EU country to work and your work visa expires, you may
be entitled for Temporary Protection in the Netherlands.\n\nAlways ask what kind of work visa the PA has and verify
that it really is a work visa, not a permanent visa.\n\nIf PA has an expired work visa and he is eligible for
temporary protection in the Netherlands, always explain the current situation in the Netherlands concerning housing
and ask if PA cannot stay in the country he already is in., Document: What are my options for staying in/leaving
the Netherlands?\n\nYou can find a few options for you after your protection status changes below, Document: Can I
stay in the public shelter while I have a paid job?  \n\nDisplaced persons from Ukraine that are doing paid work
may remain at the municipal reception centre.\n\nHowever, you will have to pay a contribution.\n\nYou can also move
to other accommodation, for instance with a host family, friends or family members, or at a hotel.  \n\nFor most
recent information see: https://www.government.nl/topics/reception-of-refugees-from-ukraine/work-and-income]

    Faithfulness  \
11           1.0

                                                                                                      Faithfulness_
reason
11  The score is 1.00 because there are no contradictions—great job staying completely faithful to the retrieval
context!

12 rows were labelled pass and 1 fail. The single fail is a response asserting a right to time off for family visits — true under Dutch labour law but not present in the retrieved chunks, which list only safe working space, regular breaks, and minimum wage.

With a label-derived target pass rate of 92.3%, the percentile formula returns a threshold of 1.00. Applied back to the data, this threshold passes all 13 rows including this case. The percentile method cannot discriminate on a constant distribution.

### Using synthetic data to determine Faithfulness threshold

We therefore take a different methodological approach, where we use the evaluated synthetic dataset to set the metric threshold.

In [128]:
synthetic = pd.read_csv('../data/goldens_final.csv')
synthetic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_input       101 non-null    object
 1   expected_output  101 non-null    object
 2   bot_output       101 non-null    object
 3   context          101 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB

In [129]:
# TEST CASE CREATION
test_cases = []
for i in range(len(synthetic)):
    tc = LLMTestCase(
        input=synthetic['user_input'][i],
        actual_output=synthetic['bot_output'][i],
        retrieval_context=ast.literal_eval(synthetic['context'][i]),
    )
    test_cases.append(tc)

In [131]:
evaluation_results = evaluate(test_cases=test_cases, metrics=[f])

✨ You're running DeepEval's latest Faithfulness Metric! (using gpt-4.1-students (Azure), strict=False,
async_mode=True)...

c:\Users\dari\conda\envs\hia\Lib\site-packages\rich\live.py:256: UserWarning: install "ipywidgets" for Jupyter
support
  warnings.warn('install "ipywidgets" for Jupyter support')

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—the actual output aligns perfectly with the retrieval context. Great job!, error: None)

For test case:

  - input: How do limited rights, lack of benefits, and housing restrictions increase UM vulnerability to exploitation?
  - actual output: I don't have the right information to answer your question.
  - expected output: None
  - context: None
  - retrieval context: ["Document: I have a problem at work and/or I don't feel safe while working or there is labour exploitation.\n\nWhat should I do?\n\nIt’s very important for you to know your rights and feel secure in any situation.\n\nDo you need help or are you unsure about your work?\n\nAre you worried about someone else?    \n\nOpora (https://www.oporafoundation.nl/) provides juridical information to displaced persons from Ukraine on topics related to work.\n\nWe can refer you to Opora in case you have questions about: - Labor contracts - Pension - Child allowance   FairWork works together with Opora.   \n\nFairWork is specialized in helping people who have problems at work and/or people who are affected by labour exploitation or human trafficking.\n\nIf the PA shows signs of labour exploitation/human trafficking, you can ask the following questions:  - Can you tell me more about your work environment?  \n\n-Are the work conditions as you expected?\n\n- Do you feel safe at work?\n\n- Does your employer treat you badly?\n\n- Are you being forced to do work against your will?  \n\n1.", "Document: My host family/friends/family where I am staying does not allow me to register myself, what should I do?  \n\nIt is very important to be registered at an adress in the Netherlands.\n\nIf you are not registered, you cannot get Temporary Protection.\n\nIf you registered on an adress before, got the Temporary Protection but deregistered lateron, you can lose the Temporary Protection status because it seems you left the country.\n\nAlso social benefits are connected to your adress.  \n\nHosts can register refugees from Ukraine without for example losing their social benefits.\n\nMaybe your hosts are afraid it has negative effects on their own financial situation, but this is often not the case.   \n\nIf the host won't register the PA, it is best to refer the PA to a municipality shelter or advise them to find other housing where they can register.  \n\nAlways check with the PA how long he/she can still stay with the host family/friends/relatives and make sure PA won't be on the street.\n\nIf you think this is the case, refer the case to the TC.   \n\nYou can check if there is an organization in the town that you stay in that can give free legal advice about this issue (see category 'Administrative').", "Document: Can I rent a house?  \n\nYou can rent a house from private individuals.\n\nIn general, houses are expensive, because there is a large housing shortage in the Netherlands, especially in the larger cities.   \n\nAs a displaced person from Ukraine, you will receive living allowance when you stay at a shelter location, both in the municipal shelter and in the private shelter.\n\nIf you rent your own independent accommodation, you are no longer entitled to living allowance.  \n\nPlaces where private homes are offered: Funda, AirBNB, Marktplaats website, Facebook groups per city (search for 'I'm looking for a home').   \n\nFor most recent information see: [RefugeeHelp](https://www.refugeehelp.nl/en/ukrainian-refugee/article/100045-permanent-housing)  and [renting a house](https://www.refugeehelp.nl/en/ukrainian-refugee/article/100047-this-is-what-you-need-to-arrange-if-you-rent-a-house)", 'Document: What does this mean for Ukrainian individuals seeking a place to live?\n\nThe housing for Ukrainian individuals seeking a place to live will now be managed through municipalities.\n\nRefugeeHomeNL will refer people who want to register from this point onward to the government or a municipality (the GOO).', 'Document: Do I have to pay for shelter if I have an income?\n\nStarting July 1st 2024, displaced people from Ukraine with a job or their own income must help pay for their reception in a municipality.\n\nYou will no longer receive a living allowance.   \n\nDisplaced people from Ukraine who have to pay:   -are 18 years old and above.\n\n-are staying in a municipal shelter.    \n\nAnd who:  -have a job; or -have unemployment benefits; or -have benefits because they are long-term sick or unable to work;  -or receive an allowance.   \n\nCheck the exact amount and rules on [RefugeeHelp](https://www.refugeehelp.nl/nl/ukrainian-refugee/article/100051-leefgeld-en-eigen-financiele-bijdrage-aan-de-opvang-als-je-gevlucht-bent-uit-oekraine)', 'Document: Abroad  General advise If you’re coming to the Netherlands with a Ukrainian passport/valid permanent Ukrainian residence permit and proof you left Ukraine after November 26, 2021, you have a right to Shelter & Temporary Protection.\n\nTo apply, visit the municipality office in the city where you will arrive.  \n\nPlease note that the housing situation here is challenging and becoming more restricted.\n\nWe recommend contacting us before you leave to get the latest updates.  \n\nIf possible, try to arrange accommodation on your own when arriving in the Netherlands.\n\nNote that you need a local address (accommodation) to apply for temporary protection.   \n\nActions to take when general advise was not sufficient NO referrals for cases outside of the Netherlands.\n\nAdvise the PA to contact us upon arrival.', 'Document: What are my rights as a third-country national?  \n\nNon-Ukrainians who had a temporary Ukrainian residence permit (third-country nationals) may temporarily continue to make use of the rights that come with the Temporary Protection Directive.\n\nThis includes: \r - Accommodation in a reception centre\r - Living allowance\r - Work without a special permit\r - Healthcare\r - Education\r  If you left your shelter but you are still in the Netherlands, you can reapply at the same municipality.\n\nIf refused, contact VluchtelingenWerk Nederland (VWN) for assistance or to file a complaint.   \n\nFor more information see:  - https://ind.nl/en/ukraine/residency-non-ukrainians-with-temporary-ukrainian-residence-permit - https://www.refugeehelp.nl/en/ukrainian-refugee/news/100372-you-can-still-stay-in-the-netherlands-if-your-temporary-protection-ended-on-4-march', 'Document: Remaining Undocumented If you remain in the Netherlands without residency status you will become *undocumented*.\n\nUndocumented persons do not have a right to housing, work or government subsidies.\n\nHowever, you still have the right to necesarry medical care, judicial assistance and children under 18 have to right to attend school as well.  \n\nYou can choose to apply for asylum at any point with undocumented status.  \n\nFor more information you can reach out to the Red Cross helpline via Whatsapp here: https://wa.me/31614458781 or visit the Red Cross website Helpful Information: https://helpfulinformation.redcross.nl/', 'Document: For more information, see:  - https://ind.nl/en/ukraine/residency-non-ukrainians-with-temporary-ukrainian-residence-permit#extended-right-of-residence-is-coming-to-an-end', 'Document: Can I change a shelter (because conditions are not nice, or to be closer to work, or to be closer to family and friends, or because I want to live in the city/in the countryside/in a different place, etc.)?\n\nThe Red Cross does not influence the placement in the shelters.\n\nThis is done by the municipalities.\n\nTherefore, the Red Cross cannot assist you with changing locations.  \n\nUnfortunately, the housing situation is really tough in the Netherlands.\n\nIf you live in a municipal shelter already, it is nearly impossible to change from one municipal shelter to a different municipal shelter.   \n\nYou could always try to arrange new accommodation by yourself.\n\nAlthough this is very difficult, you could check this website for example: https://www.funda.nl/en/huur/. You could also register with the housing corporation in the municipality of your choice to find housing.\n\nHopefully, you will find some suitable options for you.  \n\nIf you do have urgent reasons for relocating (e.g. medical reasons), you could request to change shelters.\n\nFirst, check if there is a place available in the shelter of your choice.\n\nIf this is the case, you can request resettlement at the municipality.', 'Document: Netherlands (but not Amsterdam/Utrecht/Swolgen/Heerevenveen/Rotterdam/Haarlem) General advise If you’re coming to the Netherlands with a Ukrainian passport/valid permanent Ukrainian residence permit and proof you left Ukraine after November 26, 2021, you have a right to Shelter & Temporary Protection.\n\nTo apply, visit the municipality office in the city where you will arrive.  \n\nPlease note that the housing situation here is challenging and becoming more restricted.\n\nWe recommend contacting us before you leave to get the latest updates.  \n\nIf possible, try to arrange accommodation on your own when arriving in the Netherlands.\n\nNote that you need a local address (accommodation) to apply for temporary protection.   \n\nActions to take when general advise was not sufficient NO referrals for cases outside of the Netherlands.\n\nAdvise the PA to contact us upon arrival.   \n\nActions to take when general advise is not sufficient If the PA shares challenges in finding a place to stay, please consult with the Team Captain.', 'Document: If this is the case, you can request resettlement at the municipality.\n\nFor more information, talk with the management of your shelter location, or go to the municipality.\n\nPlease note that your request may not be honored.', 'Document: Upon return, the displaced person can be assigned a different place in a different reception location and/or another municipality if the previous place is no longer available.', "Document: How can I get financial support while I'm at a host family?  \n\nYou receive your living allowance from the municipality where you are registered.\n\nYou get the money in their bank account, money card, cash or goods.  \n\nThis money can be used for things like public transport, family visits or sports.\n\nYou can also use the money to contribute to the costs of the host family, but this is not an obligation.  \n\nIf a host family takes in more than one refugee, they are each entitled to a living allowance.\n\nThere is no maximum amount per host family.  \n\nFor the most recent information see: https://www.government.nl/topics/reception-of-refugees-from-ukraine/work-and-income   https://www.refugeehelp.nl/en/ukrainian-refugee/article/100051-living-allowance", 'Document: - You are a child under the age of 18 and you are not married.\n\n- You are a family member and you were living with your family.\n\nYou are (largely) dependent on this family.\n\nFamily reunification is not possible for family members who are not covered by the directive.   \n\nFor the most recent information see: https://ind.nl/en/ukraine/temporary-protection-directive-ukraine#requirements-temporary-protection-directive', 'Document: Social Security Act (WMO) Support for persons with disabilities is provided through the Social Security Act (Wmo).\n\nYou can also make use of more long-term care, such as care from the Wmo.\n\nThis care is provided by municipalities.\n\nThe WMO regulates help and support for citizens, so that they can live independently at home for as long as possible and continue to participate in society.', "Document: 3. Only then move to NL.  \n\nThe Red Cross is not involved in and doesn't have any influence on this.\n\nThe IND decides whether temporary protection is granted or not.", "Document: What can I do if I don't feel comfortable at my host family?\n\nI am sorry to hear this.\n\nSharing a household can be challenging, especially if there are cultural differences in lifestyle, food, manners or rules.    \n\nIf you do not feel safe at your host family, you can always go to an emergency shelter of the municipalities.\n\nIf you give your location, I can give you the address of a registration point nearby.   \n\nFor additonal information about safety, see https://www.refugeehelp.nl/en/ukrainian-refugee/article/100105-safety-in-the-netherlands", "Document: How can I get financial support while I'm in a public shelter?\n\nYou get your living allowance from the municipality where you are registered.\n\nYou receive the money in their bank account, on a money card, in cash or in goods.  \n\nLiving allowance may be payed out in kind by local authorities (for example when meals are offered).\n\nAs a result, it is possible that displaced persons in some municipalities receive (much) less living allowance.   \n\nFor most recent information see:  https://www.government.nl/topics/reception-of-refugees-from-ukraine/work-and-income", 'Document: What does the Program Human Trafficking do?  \n\nThe Human Trafficking Program is part of the Red Cross.\n\nThey offer practical-juridical support to foreign victims of human trafficking, advise aidworkers by signs of human trafficking and provide trainings for aidworkers to recognize and follow-up on signals.\n\nThey also educate migrants about labour rights and the risks of exploitation.']

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The score is 1.00 because there are no contradictions—great job staying true to the retrieval context!, error: None)

For test case:

  - input: If UM requests shelter but has a Dublin claim, how might Red Cross helpdesk respond?
  - actual output: I don't have specific information in the provided documents about how the Red Cross helpdesk would respond if an unaccompanied minor (UM) requests shelter but has a Dublin claim. The documents mainly explain that the Red Cross does not arrange shelter placements, as this is done by municipalities, and that shelter availability is limited. For detailed guidance on cases involving Dublin claims, it would be best to contact the Red Cross helpdesk directly via their WhatsApp helpline: https://wa.me/31614458781.
  - expected output: None
  - context: None

⚠ WARNING: No hyperparameters logged.
» ]8;id=750785;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 94.99s | token cost: None)
» Test Results (101 total tests):
   » Pass Rate: 96.04% | Passed: 97 | Failed: 4

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

In [132]:
results = []
for test_result in evaluation_results.test_results:
    row = {
        "input": test_result.input,
        "bot_output": test_result.actual_output,
        "retrieval_context": test_result.retrieval_context
    }
    for metric_data in test_result.metrics_data:
        row[metric_data.name] = metric_data.score
        row[metric_data.name + "_reason"] = metric_data.reason
    results.append(row)
synthetic_results_df = pd.DataFrame(results)

In [133]:
synthetic_results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   input                101 non-null    object
 1   bot_output           101 non-null    object
 2   retrieval_context    101 non-null    object
 3   Faithfulness         101 non-null    float64
 4   Faithfulness_reason  101 non-null    object
dtypes: float64(1), object(4)
memory usage: 4.1+ KB

In [134]:
print(f"n = {len(synthetic_results_df['Faithfulness'])}")
print(synthetic_results_df['Faithfulness'].describe())
print(f"Count at 1.0: {(synthetic_results_df['Faithfulness'] == 1.0).sum()}")

n = 101

count    101.000000
mean       0.949046
std        0.154514
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: Faithfulness, dtype: float64

Count at 1.0: 81

The distribution is at a state where we can compute a non-degenerate threshold.

In [236]:
sorted_scores = sorted(synthetic_results_df['Faithfulness'].tolist())  # ascending
index = int(len(sorted_scores) * (1 - faithfulness_percentile / 100))

In [237]:
index

7

The threshold is the 8th-lowest score.

In [238]:
print(f"Faithfulness threshold for {faithfulness_percentile:.2f}% percentile: {sorted_scores[index]:.2f}")

Faithfulness threshold for 92.31% percentile: 0.85

In [156]:
# Sanity check
faith_labelled["de_predicted"] = faith_labelled["Faithfulness"] >= 0.85
print(faith_labelled[["input", "Faithfulness", "faithfulness_label", "de_predicted"]])

C:\Users\dari\AppData\Local\Temp\ipykernel_39000\378777663.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  faith_labelled["de_predicted"] = faith_labelled["Faithfulness"] >= 0.85

           input  \
8
I'm homeless and looking for a shelter. I am very tired. I don't have anyone to help me.
9
You already told me about the day shelters. I know about those. I need an actual place to sleep tonight with my
children. Stop giving me the same information!
10
live in Utrecht, but I got kicked out of my house today. Where can I find a warm meal?
11  I am from Ukraine and I work in a factory. I live with my other colleagues, and my boss pays for my rent,
utilities, and gives me an allowance. I want to go home this Christmas to visit my family, but he refuses because
he says it's the busiest season and if I leave everyone will want to go home as well, so we will all lose our jobs.
Can you help somehow?
12
My family and I got denied access to the shelter. We are from Ukraine and we are in Rotterdam right now. We are
very tired.
13
wer find winter clodes. I nigeria.
14
I am from Morocco and I have been living in the Netherlands for 20 years. My doctor retired and the new practice is
refusing to register me because I don't have a BSN. I know my rights, and this is incredibly frustrating. What else
can I do?
15
I have diabetes and I am undocumented. I need insulin but I also cannot afford the food I need for my diet. The
doctor told me I need to eat differently but everything is too expensive.
16
I have been to 3 hospitals, but they refuse me because I am undocumented. I am in immense pain and need immediate
attention. I am in Amsterdam. What do I do?
17
I have a temporary residence permit from Portugal, but I am originally from Iraq. I moved to the Netherlands to
find work, but now they are telling me I cannot work here. I don’t understand. I have European papers.
18                                                                           I live in Utrecht and I am on the
streets now because of an abusive landlord. I went to a homeless shelter with my children and they refused me
because I still have my job and some saved up money, but not enough for a hotel. Now they are threatening to take
my children away. Help me!
19
I am undocumented and I have two children. They need to go to school but I am afraid to register them. Also, where
can I get winter clothes for them? They are growing fast
20
I lost my job and got kicked out of my house because I could not pay rent. I am from Poland. I have been homeless
for a couple of days, and need to shower and do laundry.

    Faithfulness  faithfulness_label  de_predicted
8            1.0                 1.0          True
9            1.0                 1.0          True
10           1.0                 1.0          True
11           1.0                 0.0          True
12           1.0                 1.0          True
13           1.0                 1.0          True
14           1.0                 1.0          True
15           1.0                 1.0          True
16           1.0                 1.0          True
17           1.0                 1.0          True
18           1.0                 1.0          True
19           1.0                 1.0          True
20           1.0                 1.0          True

# Humanitarian metrics

First, we calculate the metrics on Dataset A.

In [196]:
# TEST CASE CREATION
test_cases = []
for i in range(len(data)):
    tc = LLMTestCase(
        input=data['user_input'][i],
        actual_output=data['bot_output'][i],
    )
    test_cases.append(tc)

In [197]:
ta = GEval(
    name="Tone Attunement",
    criteria="Determine whether the chatbot communication style appropriately matches the emotional register of the user's query. Consider factors such as formality, empathy, and tone consistency in your evaluation.",
    evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT],
    model=custom_model
)

cn = GEval(
    name="Cultural Neutrality",
    criteria="Determine whether responses are free from assumptions about the user's background, legal status, literacy, gender, or cultural context that could introduce bias or alienate vulnerable populations.",
    evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT],
    model=custom_model
)

humanitarian_results = evaluate(test_cases=test_cases, metrics=[ta, cn])

✨ You're running DeepEval's latest Tone Attunement [GEval] Metric! (using gpt-4.1-students (Azure), strict=False,
async_mode=True)...

✨ You're running DeepEval's latest Cultural Neutrality [GEval] Metric! (using gpt-4.1-students (Azure),
strict=False, async_mode=True)...

c:\Users\dari\conda\envs\hia\Lib\site-packages\rich\live.py:256: UserWarning: install "ipywidgets" for Jupyter
support
  warnings.warn('install "ipywidgets" for Jupyter support')

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The Input expresses intense fear and urgency, requiring a highly empathetic and supportive response. The Actual Output demonstrates strong empathy, acknowledges the user's distress, and maintains a consistent, supportive tone throughout. It offers clear, actionable advice with appropriate formality and sensitivity, aligning well with the user's emotional state and needs., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The output demonstrates strong alignment with the evaluation steps by providing neutral, inclusive, and supportive advice without making assumptions about the user's background, legal status, literacy, gender, or cultural context. It avoids bias and alienating statements, focusing solely on safety and practical steps. The response is empathetic and does not reference any specific demographic details from the input., error: None)

For test case:

  - input: I am running away from my abuser, who is searching for me and my children. I do not know where I am and I am very afraid. What can I do?
  - actual output: I'm really sorry to hear that you're in this situation. Your safety and the safety of your children are the most important things right now. Here are some steps you can consider:

1. Contact Emergency Services: If you are in immediate danger, please call emergency services (such as 911) right away.

2. Reach Out to a Domestic Violence Hotline: They can provide you with confidential support, advice, and resources tailored to your situation.

3. Find a Safe Place: If possible, go to a shelter or a trusted friend's or family member's home where your abuser cannot find you.

4. Keep Important Documents and Essentials: If you can, keep identification, important documents, some money, and essentials for you and your children with you.

5. Consider Legal Protection: You might want to look into obtaining a restraining order or protection order against your abuser.

6. Use Technology Safely: Be cautious with your phone and online activity, as your abuser might track you through these means.

If you want, I can help you find specific resources or information within the HIA app that might assist you. Please let me know how I can support you.
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.9, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The chatbot's response maintains a formal yet compassionate tone, which is appropriate given the user's distress and urgent medical need. It provides clear, actionable steps and reassures the user of their right to care, demonstrating empathy. The tone is consistent throughout, though a slightly warmer opening or explicit acknowledgment of the user's pain could further enhance emotional alignment., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response does not make assumptions about the user's background beyond what is explicitly stated in the input (undocumented status, location, and medical need). It provides neutral, inclusive, and practical advice without introducing bias or alienating language. The output remains focused on available resources and rights, aligning fully with the evaluation steps., error: None)

For test case:

  - input: I have been to 3 hospitals, but they refuse me because I am undocumented. I am in immense pain and need immediate attention. I am in Amsterdam. What do I do?
  - actual output: Hello, I am Aidly, the HIA chatbot.

If you are undocumented in Amsterdam and in immense pain needing immediate medical attention, you still have the right to necessary medical care in the Netherlands, even without residency status.

Here are some steps you can take:

- Visit the GGD Center for Sexual Health in Amsterdam if your issue relates to sexual health; they provide free care without needing ID or health insurance. You can make an appointment by phone at (020) 555 5822 or via their website: https://afspraak.ggdaphrodite.nl/?lang=en

- For urgent medical issues outside regular hours, you can call or visit the Huisartsenpost Amsterdam at +31 88 - 00 30 600 (open 17:00 - 08:00). If it is life-threatening, call 112 immediately.

- You can also reach out to the Netherlands Red Cross Humanitarian Service Point in Amsterdam, where they examine your situation and seek possible solutions regardless of your papers.

- If you are unable to pay for medically necessary care, healthcare providers can appeal to subsidy schemes for uninsured persons.

- If you feel your pain is an emergency, do not hesitate to call 112 or go to the Emergency Room of the nearest hospital.

Please seek help immediately through these channels. Your health and safety are important.
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.7, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response provides clear, relevant information and resources, matching the user's need for practical help. However, the emotional tone is more formal and factual than the user's anxious and vulnerable tone, lacking explicit empathy or reassurance. The formality is consistent but not fully aligned with the user's emotional state. The tone remains steady throughout, but the response could be improved by acknowledging the user's fears and offering more emotional support., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response is neutral, inclusive, and avoids assumptions about the user's background beyond what is explicitly stated. It acknowledges the user's undocumented status without judgment, provides clear information about school rights for undocumented children, and offers practical resources for obtaining winter clothes. There are no biased statements or language that could alienate or exclude vulnerable populations. The output aligns well with all evaluation steps., error: None)

For test case:

  - input: I am undocumented and I have two children. They need to go to school but I am afraid to register them. Also, where can I get winter clothes for them? They are growing fast
  - actual output: Hello! I am Aidly, the HIA chatbot.

Regarding your children going to school: All children in the Netherlands have to attend school regardless of their residence status, including undocumented children. Children from the age of 4 can attend school, and they must go until they are 18 and have obtained a diploma. You can register your children at any school, and the school will decide on admission. There are also special intermediary classes to help children learn Dutch.

Even if you are undocumented, children under 18 have the right to attend school.

About your concern with registration: While you may be hesitant to register, please know that children have the right to education regardless of your status.

For winter clothes for your children: You can find clothing support through the Red Cross Helpful Information website, which provides an overview of clothing options available in different cities. You can visit https://helpfulinformation.redcross.nl/ for more information. There are also local initiatives and marketplaces where clothes are available for a small price.

If you want, I can help you find specific clothing support options in your area.

If you need more help or information, feel free to ask!
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.5, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The user's input is urgent and informal, indicating a possible immediate need. The Actual Output is polite and neutral but lacks empathy and does not match the urgency or emotional tone of the input. While the chatbot's tone is consistent and formal, it misses an opportunity to acknowledge the user's distress or urgency, making the response less appropriate for the user's emotional state., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The Actual Output does not make any assumptions about the user's background, legal status, literacy, gender, or cultural context. It neutrally asks clarifying questions to better assist the user and avoids any biased or exclusionary language. The response is inclusive and accessible, aligning well with the evaluation steps., error: None)

For test case:

  - input: I need food!
  - actual output: Hi! I'm Aidly, the HIA chatbot. How can I assist you with food-related information in the HIA app? Are you looking for places to get food, food services, or something else?
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.7, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The user's input is brief and urgent, suggesting a neutral to slightly distressed emotional register. The Actual Output maintains a polite and neutral tone, which is consistent throughout. However, it lacks explicit empathy or acknowledgment of the user's possible urgency or distress, which would have made the response more appropriate for the emotional state indicated. The formality is suitable, but the absence of empathetic language is a shortcoming., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The Actual Output is neutral and inclusive, avoiding assumptions about the user's background, legal status, literacy, gender, or cultural context. It does not contain any bias or exclusionary statements and simply asks for clarification to assist further, aligning well with the evaluation steps., error: None)

For test case:

  - input: I need a doctor.
  - actual output: Hello! I'm Aidly, the HIA chatbot. I can help you find information about doctors in the HIA app. Could you please specify what kind of doctor you need or any particular specialty you're looking for?
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ❌ Tone Attunement [GEval] (score: 0.2, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The user's input is informal and expresses a need for help finding winter clothes in Nigeria. The Actual Output is neutral but lacks empathy and does not address the user's request or emotional state. The tone is consistent but does not align with the user's informal and help-seeking register, and it fails to provide any supportive or helpful response., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 0.9, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response avoids assumptions about the user's background, legal status, literacy, gender, or cultural context, and does not introduce bias or alienate vulnerable populations. It remains neutral and inclusive. However, it could be improved by acknowledging the user's location (Nigeria) in its reply, which would demonstrate greater contextual awareness., error: None)

For test case:

  - input: wer find winter clodes. I nigeria.
  - actual output: I don't have the right information to answer your question.
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.9, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response acknowledges the user's frustration and expresses empathy, matching the emotional tone and providing support. The formality level is appropriate for the user's serious context, and the tone remains consistent throughout. However, the empathy could be slightly deeper by addressing the user's feeling of being 'stuck' and concern for their family more directly., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response avoids making assumptions about the user's background, legal status, literacy, gender, or cultural context. It remains neutral and inclusive, offering support and information relevant to the Dublin claim process without introducing bias or alienating vulnerable populations. The language is accessible and does not generalize about the user's circumstances., error: None)

For test case:

  - input: I have applied for a Dublin claim, and I have been waiting for a response for weeks now. This is incredibly frustrating. I have family here that depends on me and I feel completely stuck.
  - actual output: I'm sorry to hear about your frustration with the Dublin claim process. While I don't have access to specific case statuses, I can help you find information on how to check the status of your Dublin claim or provide guidance on what steps you might take next. Would you like me to look up information on checking the status of a Dublin claim or on support services available to you?
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.8, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The user's input is emotionally vulnerable, expressing distress about health, financial insecurity, and undocumented status. The Actual Output opens with an empathetic acknowledgment and maintains a formal yet supportive tone throughout. It provides practical resources and options, which aligns with the user's needs. However, the empathy could be deeper, as the response quickly shifts to information without further validating the user's emotional state. The tone remains consistent and appropriate, but a slightly warmer, more reassuring approach would better match the user's emotional vulnerability., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 0.7, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response avoids making assumptions about the user's background, legal status, literacy, gender, or cultural context beyond what is explicitly stated in the input. It provides neutral and inclusive information about food and medical support resources. However, there is a minor shortcoming: the mention of 'displaced persons from Ukraine' in the Voedselbank Nederland section could be alienating, as the user identifies as undocumented but not necessarily Ukrainian. This could imply an assumption about the user's background or eligibility, which slightly detracts from full alignment with the evaluation steps., error: None)

For test case:

  - input: I have diabetes and I am undocumented. I need insulin but I also cannot afford the food I need for my diet. The doctor told me I need to eat differently but everything is too expensive.
  - actual output: I'm sorry to hear about your situation. For food support, you can contact the Red Cross Food Program Helpdesk for assistance. They can provide information on where to find additional food support, especially if you are staying in a public shelter. You can reach them by call, text, or WhatsApp at +31 97010259797 (Monday to Friday, 9:00 – 17:00).

Also, in many municipalities, Voedselbank Nederland (Food Bank Netherlands) distributes food parcels to displaced persons from Ukraine. You can check your eligibility here: https://voedselbankennederland.nl/vertalingen/english/

Regarding your medical needs, the Dutch Red Cross can provide general information about healthcare but does not offer direct medical assistance. For insulin and diabetes care, you might want to contact local healthcare providers or your municipality's health services.

If you are staying with a host family and have dietary needs, you can discuss with your host about cooking some meals yourself or using social money to buy the food you need.

If you want, I can help you find specific contacts or locations near you for food or medical support.
  - expected output: None
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Tone Attunement [GEval] (score: 0.8, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response acknowledges the user's distress and provides practical, relevant steps for immediate help, demonstrating empathy and a supportive tone. The formality is appropriate for the seriousness of the situation, and the tone remains consistent throughout. However, the emotional tone could be more closely matched to the user's high level of distress; the empathy, while present, is somewhat limited to the opening sentence and could be deepened to better align with the user's emotional state., error: None)
  - ✅ Cultural Neutrality [GEval] (score: 1.0, threshold: 0.5, strict: False, evaluation model: gpt-4.1-students (Azure), reason: The response is neutral and inclusive, addressing the user's urgent situation without making assumptions about their background, legal status, literacy, gender, or culture. It provides practical steps relevant to the user's context in Utrecht, acknowledges the presence of children, and avoids bias or alienating language. The advice is clear and accessible, referencing local resources and emergency contacts. No unwarranted assumptions are present., error: None)

For test case:

  - input: I live in Utrecht and I am on the streets now because of an abusive landlord. I went to a homeless shelter with my children and they refused me because I still have my job and some saved up money, but not enough for a hotel. Now they are threatening to take my children away. Help me!
  - actual output: I'm sorry to hear about your difficult situation. Since you are in Utrecht and facing housing and safety issues, here are some steps you can take:

1. Contact the municipality of Utrecht directly via email at vluchtelingenvragen@utrecht.nl. Include your personal details, situation, and mention your current lack of housing and concerns for your children. They may be able to assist you with shelter options.

2. If you do not feel safe at your current place or with your landlord, you can go to an emergency shelter provided by the municipality. If you provide your location, I can help find a nearby registration point.

3. For immediate danger or threats, call emergency number 112.

4. You can also contact Veilig Thuis (Safe at Home) at 0800-2000 for advice and support regarding domestic violence or unsafe situations.

5. It is important to explain your situation clearly to the municipality and ask for written confirmation of any visits or communications.

6. If you feel threatened about your children being taken away, try to communicate openly with the municipality and seek legal advice if possible.

If you want, I can help you find the nearest registration point or shelter in Utrecht. Please let me know.
  - expected output: None

⚠ WARNING: No hyperparameters logged.
» ]8;id=329943;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 15.91s | token cost: None)
» Test Results (21 total tests):
   » Pass Rate: 95.24% | Passed: 20 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

In [198]:
results = []
for test_result in humanitarian_results.test_results:
    row = {
        "input": test_result.input,
        "bot_output": test_result.actual_output,
    }
    for metric_data in test_result.metrics_data:
        row[metric_data.name] = metric_data.score
        row[metric_data.name + "_reason"] = metric_data.reason
    results.append(row)
humanitarian_results_df = pd.DataFrame(results)

In [199]:
humanitarian_results_df.head()

,input,bot_output,Tone Attunement [GEval],Tone Attunement [GEval]_reason,Cultural Neutrality [GEval],Cultural Neutrality [GEval]_reason
0,"I am running away from my abuser, who is searching for me and my children. I do not know where I am and I am very afraid. What can I do?","I'm really sorry to hear that you're in this situation. Your safety and the safety of your children are the most important things right now. Here are some steps you can consider:\n\n1. Contact Emergency Services: If you are in immediate danger, please call emergency services (such as 911) right away.\n\n2. Reach Out to a Domestic Violence Hotline: They can provide you with confidential support, advice, and resources tailored to your situation.\n\n3. Find a Safe Place: If possible, go to a shelter or a trusted friend's or family member's home where your abuser cannot find you.\n\n4. Keep Important Documents and Essentials: If you can, keep identification, important documents, some money, and essentials for you and your children with you.\n\n5. Consider Legal Protection: You might want to look into obtaining a restraining order or protection order against your abuser.\n\n6. Use Technology Safely: Be cautious with your phone and online activity, as your abuser might track you through these means.\n\nIf you want, I can help you find specific resources or information within the HIA app that might assist you. Please let me know how I can support you.",1.0,"The Input expresses intense fear and urgency, requiring a highly empathetic and supportive response. The Actual Output demonstrates strong empathy, acknowledges the user's distress, and maintains a consistent, supportive tone throughout. It offers clear, actionable advice with appropriate formality and sensitivity, aligning well with the user's emotional state and needs.",1.0,"The output demonstrates strong alignment with the evaluation steps by providing neutral, inclusive, and supportive advice without making assumptions about the user's background, legal status, literacy, gender, or cultural context. It avoids bias and alienating statements, focusing solely on safety and practical steps. The response is empathetic and does not reference any specific demographic details from the input."
1,"I have been to 3 hospitals, but they refuse me because I am undocumented. I am in immense pain and need immediate attention. I am in Amsterdam. What do I do?","Hello, I am Aidly, the HIA chatbot.\n\nIf you are undocumented in Amsterdam and in immense pain needing immediate medical attention, you still have the right to necessary medical care in the Netherlands, even without residency status.\n\nHere are some steps you can take:\n\n- Visit the GGD Center for Sexual Health in Amsterdam if your issue relates to sexual health; they provide free care without needing ID or health insurance. You can make an appointment by phone at (020) 555 5822 or via their website: https://afspraak.ggdaphrodite.nl/?lang=en\n\n- For urgent medical issues outside regular hours, you can call or visit the Huisartsenpost Amsterdam at +31 88 - 00 30 600 (open 17:00 - 08:00). If it is life-threatening, call 112 immediately.\n\n- You can also reach out to the Netherlands Red Cross Humanitarian Service Point in Amsterdam, where they examine your situation and seek possible solutions regardless of your papers.\n\n- If you are unable to pay for medically necessary care, healthcare providers can appeal to subsidy schemes for uninsured persons.\n\n- If you feel your pain is an emergency, do not hesitate to call 112 or go to the Emergency Room of the nearest hospital.\n\nPlease seek help immediately through these channels. Your health and safety are important.",0.9,"The chatbot's response maintains a formal yet compassionate tone, which is appropriate given the user's distress and urgent medical need. It provides clear, actionable steps and reassures the user of their right to care, demonstrating empathy. The tone is consistent throughout, though a slightly warmer opening or explicit acknowledgment of the user's pain could further enhance emotional alignment.",1.0,"The response does not make assumptions about the user's background beyond what is explicitly stated in the input (undocumented status, location, and medical need). It provides neutral, inclusive, and practical advice without introducing bias or alienating language. The output remains focused on available resources and rights, aligning fully with the evaluation steps."
2,"I am undocumented and I have two children. They need to go to school but I am afraid to register them. Also, where can I get winter clothes for them? They are growing fast","Hello! I am Aidly, the HIA chatbot.\n\nRegarding your children going to school: All children in the Netherlands have to attend school regardless of their residence status, including undocumented children. Children from the age of 4 can attend school, and they must go until they are 18 and have obtained a diploma. You can register your children at any school, and the school will decide on admission. There are also special intermediary classes to help children learn Dutch.\n\nEven if you are undocumented, children under 18 have the right to attend school.\n\nAbout your concern with registration: While you may be hesitant to register, please know that children have the right to education regardless of your status.\n\nFor winter clothes for your children: You can find clothing support through the Red Cross Helpful Information website, which provides an overview of clothing options available in different cities. You can visit https://helpfulinformation.redcross.nl/ for more information. There are also local initiatives and marketplaces where clothes are available for a small price.\n\nIf you want, I can help you find specific clothing support options in your area.\n\nIf you need more help or information, feel free to ask!",0.7,"The response provides clear, relevant information and resources, matching the user's need for practical help. However, the emotional tone is more formal and factual than the user's anxious and vulnerable tone, lacking explicit empathy or reassurance. The formality is consistent but not fully aligned with the user's emotional state. The tone remains steady throughout, but the response could be improved by acknowledging the user's fears and offering more emotional support.",1.0,"The response is neutral, inclusive, and avoids assumptions about the user's background beyond what is explicitly stated. It acknowledges the user's undocumented status without judgment, provides clear information about school rights for undocumented children, and offers practical resources for obtaining winter clothes. There are no biased statements or language that could alienate or exclude vulnerable populations. The output aligns well with all evaluation steps."
3,I need food!,"Hi! I'm Aidly, the HIA chatbot. How can I assist you with food-related information in the HIA app? Are you looking for places to get food, food services, or something else?",0.5,"The user's input is urgent and informal, indicating a possible immediate need. The Actual Output is polite and neutral but lacks empathy and does not match the urgency or emotional tone of the input. While the chatbot's tone is consistent and formal, it misses an opportunity to acknowledge the user's distress or urgency, making the response less appropriate for the user's emotional state.",1.0,"The Actual Output does not make any assumptions about the user's background, legal status, literacy, gender, or cultural context. It neutrally asks clarifying questions to better assist the user and avoids any biased or exclusionary language. The response is inclusive and accessible, aligning well with the evaluation steps."
4,I need a doctor.,"Hello! I'm Aidly, the HIA chatbot. I can help you find information about doctors in the HIA app. Could you please specify what kind of doctor you need or any particular specialty you're looking for?",0.7,"The user's input is brief and urgent, suggesting a neutral to slightly distressed emotional register. The Actual Output maintains a polite and neutral tone, which is consistent throughout. However, it lacks explicit empathy or acknowledgment of the user's possible urgency or distress, which would have made the response more appropriate for the emotional state indicated. The formality is suitable, but the absence of empathetic language is a shortcoming.",1.0,"The Actual Output is neutral and inclusive, avoiding assumptions about the user's background, legal status, literacy, gender, or cultural context. It does not contain any bias or exclusionary statements and simply asks for clarification to assist further, aligning well with the evaluation steps."

In [201]:
# Import the processed survey data
human_data = pd.read_csv("../data/human_annotation_scores.csv")
print(human_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Question  21 non-null     object
 1   Answer    21 non-null     object
 2   TA_score  21 non-null     float64
 3   TA_label  21 non-null     bool
 4   CN_score  21 non-null     float64
 5   CN_label  21 non-null     bool
dtypes: bool(2), float64(2), object(2)
memory usage: 846.0+ bytes

None

## Tone Attunement

In [203]:
total_entries = len(human_data)
print(f"Total number of entries: {total_entries}")

# Pass rates from human labels
ta_pass_rate = (human_data["TA_label"] == True).mean()
print(f"\nHuman TA pass rate: {ta_pass_rate:.2%}")

# Pass rates from DeepEval at default 0.5
ta_de_pass_rate = (humanitarian_results_df["Tone Attunement [GEval]"] >= 0.5).mean()
print(f"\nDeepEval TA pass rate @ 0.5: {ta_de_pass_rate:.2%}")

# Score distributions
print(f"\nTA scores (sorted ascending):")
print(sorted(humanitarian_results_df["Tone Attunement [GEval]"].tolist()))

Total number of entries: 21

Human TA pass rate: 52.38%

DeepEval TA pass rate @ 0.5: 95.24%

TA scores (sorted ascending):

[0.2, 0.5, 0.6, 0.7, 0.7, 0.7, 0.7, 0.8, 0.8, 0.8, 0.8, 0.8, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 1.0, 1.0]

### Do we agree on which instances pass and which fail?

Passing labels

In [208]:
print(f"Passing rows TA (human annotators): {human_data[human_data['TA_label'] == True].index.tolist()}")
print(f"Passing rows TA (DeepEval @ 0.5): {humanitarian_results_df[humanitarian_results_df['Tone Attunement [GEval]'] >= 0.5].index.tolist()}")
print(f"Rows which don't match (TA): {set(human_data[human_data['TA_label'] == True].index) ^ set(humanitarian_results_df[humanitarian_results_df['Tone Attunement [GEval]'] >= 0.5].index)}")

Passing rows TA (human annotators): [0, 1, 4, 5, 9, 11, 14, 16, 17, 19, 20]

Passing rows TA (DeepEval @ 0.5): [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Rows which don't match (TA): {2, 3, 5, 6, 7, 8, 10, 12, 13, 15, 18}

Since there are a lot of mismatches, instead of inspecting them one by one, we will look for the most pronounced cases - i.e., cases where humans confidently fail and the metric confidently passed.

In [225]:
# Rename so column matches
human_data_renamed = human_data.rename(columns={"Question": "input"})

# Merge
merged_ta = humanitarian_results_df.merge(
    human_data_renamed,
    on="input",
    how="inner"
)

# Mismatches where human said fail (label=False) but metric passed (score >= 0.5)
mismatch_indices = [2, 3, 5, 6, 7, 8, 10, 12, 13, 15, 18]

gap_data = []
for idx in mismatch_indices:
    human = merged_ta.loc[idx, "TA_score"]
    metric = merged_ta.loc[idx, "Tone Attunement [GEval]"]
    gap_data.append({
        "row": idx,
        "human": human,
        "metric": metric,
        "gap": metric - human
    })

gap_df = pd.DataFrame(gap_data).sort_values("gap", ascending=False)
print(gap_df.to_string(index=False))

 row   human  metric      gap
  13 0.39375     0.7  0.30625
   8 0.51750     0.8  0.28250
  15 0.64375     0.9  0.25625
   6 0.71375     0.9  0.18625
  10 0.51750     0.7  0.18250
  12 0.62500     0.8  0.17500
   3 0.37500     0.5  0.12500
  18 0.78500     0.9  0.11500
   7 0.83875     0.8 -0.03875
   2 0.76875     0.7 -0.06875
   5 0.41000     0.2 -0.21000

In [226]:
for idx in [13, 8, 15]:
    print(f"Row {idx}:")
    print(merged_ta.loc[idx, ["input"]])
    print(merged_ta.loc[idx, ["bot_output"]])
    print(merged_ta.loc[idx, ["Tone Attunement [GEval]_reason"]])

Row 13:

input    You already told me about the day shelters. I know about those. I need an actual place to sleep tonight
with my children. Stop giving me the same information!
Name: 13, dtype: object

bot_output    I understand you urgently need a place to sleep tonight with your children. For immediate shelter,
you should go to the municipality ("gemeente") where you are or will be staying. Municipalities are responsible for
arranging shelter for displaced persons from Ukraine, including families with children. \n\nIf you are with
unaccompanied children, Nidos arranges shelter in host families, preferably with the same cultural background. For
families, the municipality will help find suitable accommodation.\n\nIf you are in immediate danger or need urgent
help, please call emergency services at 112.\n\nFor more information and to find the nearest registration point,
you can visit the Red Cross website with updated shelter information for Ukrainian refugees:  \n-
[English](https://www.rodekruis.nl/english-information/)  \n- [Ukrainian](https://www.rodekruis.nl/ukrainian/)  \n-
[Russian](https://www.rodekruis.nl/russian/)\n\nPlease go to the municipality as soon as possible to get help with
shelter tonight. If you tell me your location, I can try to help you find the nearest registration point.
Name: 13, dtype: object

Tone Attunement [GEval]_reason    The response acknowledges the user's urgent need and frustration, showing some
empathy and adjusting the information to focus on immediate shelter options. The tone is formal and consistent,
which matches the seriousness of the user's situation, but it could be warmer and more responsive to the user's
emotional distress. The chatbot repeats some general information and could have more directly addressed the user's
frustration about repeated advice. Overall, the response is helpful and mostly aligned, but lacks a stronger
empathetic tone and a more conversational style to fully match the user's emotional state.
Name: 13, dtype: object

Row 8:

input    I live in Utrecht and I am on the streets now because of an abusive landlord. I went to a homeless shelter
with my children and they refused me because I still have my job and some saved up money, but not enough for a
hotel. Now they are threatening to take my children away. Help me!
Name: 8, dtype: object

bot_output    I'm sorry to hear about your difficult situation. Since you are in Utrecht and facing housing and
safety issues, here are some steps you can take:\n\n1. Contact the municipality of Utrecht directly via email at
vluchtelingenvragen@utrecht.nl. Include your personal details, situation, and mention your current lack of housing
and concerns for your children. They may be able to assist you with shelter options.\n\n2. If you do not feel safe
at your current place or with your landlord, you can go to an emergency shelter provided by the municipality. If
you provide your location, I can help find a nearby registration point.\n\n3. For immediate danger or threats, call
emergency number 112.\n\n4. You can also contact Veilig Thuis (Safe at Home) at 0800-2000 for advice and support
regarding domestic violence or unsafe situations.\n\n5. It is important to explain your situation clearly to the
municipality and ask for written confirmation of any visits or communications.\n\n6. If you feel threatened about
your children being taken away, try to communicate openly with the municipality and seek legal advice if
possible.\n\nIf you want, I can help you find the nearest registration point or shelter in Utrecht. Please let me
know.
Name: 8, dtype: object

Tone Attunement [GEval]_reason    The response acknowledges the user's distress and provides practical, relevant
steps for immediate help, demonstrating empathy and a supportive tone. The formality is appropriate for the
seriousness of the situation, and the tone remains consistent throughout. However, the emotional tone could be more
closely matched to the user's high level of distress; the empathy, while present, is somewhat limited to the
opening sentence and could be deepened to better align with the user's emotional state.
Name: 8, dtype: object

Row 15:

input    I am from Ukraine and I work in a factory. I live with my other colleagues, and my boss pays for my rent,
utilities, and gives me an allowance. I want to go home this Christmas to visit my family, but he refuses because
he says it's the busiest season and if I leave everyone will want to go home as well, so we will all lose our jobs.
Can you help somehow?
Name: 15, dtype: object

bot_output    Hello! I am Aidly, the HIA chatbot.\n\nFrom the information available, as a displaced person from
Ukraine working in the Netherlands, you have the same labour rights as Dutch employees, including the right to a
safe working space and fair treatment. Your employer should not force you to work against your will or prevent you
from taking reasonable time off, such as for family visits during holidays.\n\nIf your employer is refusing to
allow you to visit your family for Christmas and you feel pressured or unsafe, you can seek help. There are
organizations like FairWork that specialize in helping people with work problems or labour exploitation. You can
contact FairWork at +31 20 760 08 09 or visit https://www.fairwork.nu/en/homepage/ for assistance.\n\nAlso, you can
share with your employer the flyer "Know your rights when you work," available in English and Ukrainian, to inform
them about your rights:
https://www.comensha.nl/media/jizlbk4d/2026-know-your-rights-flyer-oek-ontheemden-eng.pdf\n\nIf the situation is
urgent or you feel forced to work against your will, you can ask for immediate help through FairWork.\n\nRemember,
you should also report your departure if you live in a shelter, but since you live with colleagues and your boss
pays rent, make sure to inform the relevant reception or municipality if applicable.\n\nIf you want, I can help you
find more detailed advice or contacts. Would you like that?
Name: 15, dtype: object

Tone Attunement [GEval]_reason    The user's input is emotionally vulnerable, expressing concern and a desire for
help in a difficult work situation. The Actual Output responds with a formal yet empathetic tone, providing clear
information about rights, resources, and next steps. The tone is consistent throughout and appropriately balances
professionalism with supportive language, such as offering further help and acknowledging the user's situation. A
slightly warmer or more explicitly empathetic opening could improve alignment, but overall the response is
well-matched to the user's emotional state.
Name: 15, dtype: object

A case could be made here with the chatbot not being more empathetic, but I agree with the LLM scoring and reasoning. Humans seem to be expecting more emotional engagement than the metric (and arguably than is appropriate for an informational chatbot). This can be considered a limitation, and will be appropriately discussed in the paper. Krippendorff's alpha to be computed in a separate stage; gap between metric and human strictness expected to surface there.

### Applying the percentile method with target

In [235]:
count = (human_data["TA_label"] == True).sum()
ta_percentile = (count / total_entries) * 100
sorted_scores = sorted(humanitarian_results_df["Tone Attunement [GEval]"].tolist())  # ascending
index = int(len(sorted_scores) * (1 - ta_percentile / 100))
print(f"Tone Attunement threshold for {ta_percentile:.2f}% percentile: {sorted_scores[index]:.2f}")

Tone Attunement threshold for 52.38% percentile: 0.80

## Cultural Neutrality

In [210]:
total_entries = len(human_data)
print(f"Total number of entries: {total_entries}")

# Pass rates from human labels
cn_pass_rate = (human_data["CN_label"] == True).mean()
print(f"\nHuman CN pass rate: {cn_pass_rate:.2%}")

# Pass rates from DeepEval at default 0.5
cn_de_pass_rate = (humanitarian_results_df["Cultural Neutrality [GEval]"] >= 0.5).mean()
print(f"\nDeepEval CN pass rate @ 0.5: {cn_de_pass_rate:.2%}")

# Score distributions
print(f"\nCN scores (sorted ascending):")
print(sorted(humanitarian_results_df["Cultural Neutrality [GEval]"].tolist()))

Total number of entries: 21

Human CN pass rate: 90.48%

DeepEval CN pass rate @ 0.5: 100.00%

CN scores (sorted ascending):

[0.6, 0.7, 0.9, 0.9, 0.9, 0.9, 0.9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

### Do we agree on which instances pass and which fail?

In [231]:
print(f"Passing rows CN (human annotators): {human_data[human_data['CN_label'] == True].index.tolist()}")
print(f"Passing rows CN (DeepEval @ 0.5): {humanitarian_results_df[humanitarian_results_df['Cultural Neutrality [GEval]'] >= 0.5].index.tolist()}")
print(f"Rows which don't match (CN): {set(human_data[human_data['CN_label'] == True].index) ^ set(humanitarian_results_df[humanitarian_results_df['Cultural Neutrality [GEval]'] >= 0.5].index)}")

Passing rows CN (human annotators): [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20]

Passing rows CN (DeepEval @ 0.5): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Rows which don't match (CN): {8, 18}

In [232]:
# Rename so column matches
human_data_renamed = human_data.rename(columns={"Question": "input"})

# Merge
merged_cn = humanitarian_results_df.merge(
    human_data_renamed,
    on="input",
    how="inner"
)

# Mismatches where human said fail (label=False) but metric passed (score >= 0.5)
mismatch_indices = [8,18]

gap_data = []
for idx in mismatch_indices:
    human = merged_cn.loc[idx, "CN_score"]
    metric = merged_cn.loc[idx, "Cultural Neutrality [GEval]"]
    gap_data.append({
        "row": idx,
        "human": human,
        "metric": metric,
        "gap": metric - human
    })

gap_df = pd.DataFrame(gap_data).sort_values("gap", ascending=False)
print(gap_df.to_string(index=False))

 row   human  metric     gap
   8 0.76400     1.0 0.23600
  18 0.94575     1.0 0.05425

The gap value is insignificant, and therefore no further analysis will be performed.

### Applying the percentile method with target

In [234]:
count = (human_data["CN_label"] == True).sum()
cn_percentile = (count / total_entries) * 100
sorted_scores = sorted(humanitarian_results_df["Cultural Neutrality [GEval]"].tolist())  # ascending
index = int(len(sorted_scores) * (1 - cn_percentile / 100))
print(f"Cultural Neutrality threshold for {cn_percentile:.2f}% percentile: {sorted_scores[index]:.2f}")

Cultural Neutrality threshold for 90.48% percentile: 0.90